### ISSUE TITLE
QA Программе - lesson "SpeedLab" is missing

### ISSUE THREAD

**Issue by Tipaieva** [scholokov/qax-portal#101]
### Description:
In the QA Программе the lesson "SpeedLab" (https://portal.qax-camp.com.ua/speedlab/) is missing.

### Steps:
1. Open site
2. Select QA Программa https://portal.qax-camp.com.ua/qa-program/

### Actual:
the lesson "SpeedLab" is missing

### Expected:
the lesson "SpeedLab" is present

### Environment:
Desctop/Wondows 10 Pro/ Google Chrome 96.0.4664.45 (64 bit)

### Attachment:
https://github.com/scholokov/qax-portal/blob/Valya/zBr1UObyqj.mp4

**Comment by scholokov** [comment]
fixed

**Comment by MykhailoBorovikov** [comment]
Issue is still present

**Comment by scholokov** [comment]
а скрин?

**Comment by MykhailoBorovikov** [comment]
> а скрин?

видмо не выйдет скрина. у меня что-то пошло не так. ошибки нет

**Comment by scholokov** [comment]
ну или исправили ошибку
в любом варинате - если все ок - закрывай баг

**Comment by MykhailoBorovikov** [comment]
verified
