### ISSUE TITLE
QA Программа - lesson "JSON vs XML vs HTML" is missing

### ISSUE THREAD

**Issue by Tipaieva** [scholokov/qax-portal#104]
### Description:
In the QA Программе the lesson "JSON vs XML vs HTML" (https://portal.qax-camp.com.ua/json-xml-html/) is missing.
The lesson "JSON vs XML vs HTML" contains one article and one video lesson.

### Steps:
1. Open site
2. Select QA Программa https://portal.qax-camp.com.ua/qa-program/

### Actual:
the lesson "JSON vs XML vs HTML" **is missing**

### Expected:
the lesson "JSON vs XML vs HTML" **is present**

### Environment:
Desctop/Wondows 10 Pro/ Google Chrome 96.0.4664.45 (64 bit)

### Attachment:
![image](https://user-images.githubusercontent.com/92110820/143765349-9d6b4c7c-58d3-49c9-b952-d8da4e177965.png)

**Comment by scholokov** [comment]
fixed
added to REST, SOAP, API course

**Comment by Tipaieva** [comment]
verified
