### ISSUE TITLE
QA Программa - lesson "Postman" is missing

### ISSUE THREAD

**Issue by Tipaieva** [scholokov/qax-portal#106]
### Description:
In the QA Программе the lesson "Postman" (https://portal.qax-camp.com.ua/postman/) is missing.

### Steps:
1. Open site
2. Select QA Программa https://portal.qax-camp.com.ua/qa-program/

### Actual:
the lesson "Postman" **is missing**

### Expected:
the lesson "Postman" **is present**

### Environment:
Desctop/Wondows 10 Pro/ Google Chrome 96.0.4664.45 (64 bit)

### Attachment:
![image](https://user-images.githubusercontent.com/92110820/143767414-abd37701-d85d-46aa-8fbb-503217720f59.png)

**Comment by scholokov** [comment]
добавлен урок Postman
в курс Postman
блок Web technologies
обязателен к прохождению

**Comment by Tipaieva** [comment]
verified
