### ISSUE TITLE
QA Программa - lesson "Total Commander" is missing

### ISSUE THREAD

**Issue by Tipaieva** [scholokov/qax-portal#107]
### Description:
In the QA Программе the lesson "Total Commander" (https://portal.qax-camp.com.ua/total-commander/) is missing.

### Steps:
1. Open site
2. Select QA Программa https://portal.qax-camp.com.ua/qa-program/

### Actual:
the lesson "Total Commander" **is missing**

### Expected:
the lesson "Total Commander" **is present**

### Environment:
Desctop/Wondows 10 Pro/ Google Chrome 96.0.4664.45 (64 bit)

### Attachment:
![image](https://user-images.githubusercontent.com/92110820/143768093-a65663f1-5d93-48aa-86c9-2c76787be3cd.png)

**Comment by scholokov** [comment]
fixed

**Comment by MykhailoBorovikov** [comment]
Verified
