### ISSUE TITLE
QA Программa - lesson "Test Data Generation Tools" is missing

### ISSUE THREAD

**Issue by Tipaieva** [scholokov/qax-portal#108]
### Description:
In the QA Программе the lesson "Test Data Generation Tools" (https://portal.qax-camp.com.ua/test-data-generation-tools/) is missing.

### Steps:
1. Open site
2. Select QA Программa https://portal.qax-camp.com.ua/qa-program/

### Actual:
the lesson "Test Data Generation Tools" **is missing**

### Expected:
the lesson "Test Data Generation Tools" **is present**

### Environment:
Desctop/Wondows 10 Pro/ Google Chrome 96.0.4664.45 (64 bit)

### Attachment:
![image](https://user-images.githubusercontent.com/92110820/143768314-14ead56f-09fe-4260-9c7d-2fcf5dfa3e3d.png)

**Comment by scholokov** [comment]
fixed

**Comment by MykhailoBorovikov** [comment]
verified
