### ISSUE TITLE
QA Программa - the lesson "Веселое выступление о необычных дизайнах продуктов" is missing

### ISSUE THREAD

**Issue by Tipaieva** [scholokov/qax-portal#109]
### Description:
In the QA Программе the lesson "Веселое выступление о необычных дизайнах продуктов" (https://portal.qax-camp.com.ua/extraordinary-design/) is missing.

### Steps:

1. Open site
2. Select QA Программa https://portal.qax-camp.com.ua/qa-program/

### Actual:
the lesson "Веселое выступление о необычных дизайнах продуктов" **is missing**

### Expected:
the lesson "Веселое выступление о необычных дизайнах продуктов" **is present**

### Environment:
Desctop/Wondows 10 Pro/ Google Chrome 96.0.4664.45 (64 bit)

### Attachment:
![image](https://user-images.githubusercontent.com/92110820/143768484-9dc1b47b-7994-446e-9178-72cb2aaeec2e.png)

**Comment by scholokov** [comment]
добавлен урок
Веселое выступление о необычных дизайнах продуктов
в курс
UI
в блок
Web, Mobile, UI – Testing
необязателен, для прохождения

**Comment by Tipaieva** [comment]
verified
