### ISSUE TITLE
QA Программa - lesson "SessionBox" is missing

### ISSUE THREAD

**Issue by Tipaieva** [scholokov/qax-portal#110]
### Description:
In the QA Программе the lesson "SessionBox" (https://portal.qax-camp.com.ua/sessionbox/) is missing.

### Steps:

1. Open site
2. Select QA Программa https://portal.qax-camp.com.ua/qa-program/

### Actual:
the lesson "SessionBox" **is missing**

### Expected:
the lesson "SessionBox" **is present**

### Environment:
Desctop/Wondows 10 Pro/ Google Chrome 96.0.4664.45 (64 bit)

### Attachment:
![image](https://user-images.githubusercontent.com/92110820/143769366-786968a6-a53a-4cba-83dd-bf40c5f942bf.png)

**Comment by scholokov** [comment]
fixed

**Comment by MykhailoBorovikov** [comment]
verified
