### ISSUE TITLE
QA Программa - lesson "RegexOne" is missing

### ISSUE THREAD

**Issue by Tipaieva** [scholokov/qax-portal#111]
### Description:
In the QA Программе the lesson "RegexOne" (https://portal.qax-camp.com.ua/regexone/) is missing.

### Steps:
1. Open site
2. Select QA Программa https://portal.qax-camp.com.ua/qa-program/

### Actual:
the lesson "RegexOne" **is missing**

### Expected:
the lesson "RegexOne" **is present**

### Environment:
Desctop/Wondows 10 Pro/ Google Chrome 96.0.4664.45 (64 bit)

### Attachment:
![image](https://user-images.githubusercontent.com/92110820/143769615-f79ae43e-092e-4f2b-ae22-542800481fcb.png)

**Comment by scholokov** [comment]
fixed

**Comment by MykhailoBorovikov** [comment]
verified
