### ISSUE TITLE
QA Программa - lesson "Гайд по тестированию локализации и интернационализации, а также большой и полезный checklist" is missing 

### ISSUE THREAD

**Issue by Tipaieva** [scholokov/qax-portal#114]
### Description:
In the QA Программе the lesson "Гайд по тестированию локализации и интернационализации, а также большой и полезный checklist" (https://portal.qax-camp.com.ua/%d0%b3%d0%b0%d0%b9%d0%b4-%d0%bf%d0%be-%d1%82%d0%b5%d1%81%d1%82%d0%b8%d1%80%d0%be%d0%b2%d0%b0%d0%bd%d0%b8%d1%8e-%d0%bb%d0%be%d0%ba%d0%b0%d0%bb%d0%b8%d0%b7%d0%b0%d1%86%d0%b8%d0%b8-%d0%b8-%d0%b8%d0%bd/) is missing

### Steps:

1. Open site
2. Select QA Программa https://portal.qax-camp.com.ua/qa-program/

### Actual:
the lesson "Гайд по тестированию локализации и интернационализации, а также большой и полезный checklist" **is missing**

### Expected:
the lesson "Гайд по тестированию локализации и интернационализации, а также большой и полезный checklist" **is present**

### Environment:
Desctop/Wondows 10 Pro/ Google Chrome 96.0.4664.45 (64 bit)

### Attachment:
![image](https://user-images.githubusercontent.com/92110820/143770099-d26c46c9-4df6-484f-8620-9cac72ad20b5.png)

**Comment by MykhailoBorovikov** [comment]
bug fixed and verified
