### ISSUE TITLE
QA Программa - lesson "Metro Retro" is missing

### ISSUE THREAD

**Issue by Tipaieva** [scholokov/qax-portal#115]
### Description:
In the QA Программе the lesson "Metro Retro" (https://portal.qax-camp.com.ua/metro-retro/) is missing

### Steps:
1. Open site
2. Select QA Программa https://portal.qax-camp.com.ua/qa-program/

### Actual:
the lesson "Metro Retro" **is missing**

### Expected:
the lesson "Metro Retro" **is present**

### Environment:
Desctop/Wondows 10 Pro/ Google Chrome 96.0.4664.45 (64 bit)

### Attachment:
![image](https://user-images.githubusercontent.com/92110820/143770288-5244ca88-8e78-4252-817d-07920f7b459b.png)

**Comment by scholokov** [comment]
fixed

**Comment by MykhailoBorovikov** [comment]
Issue is still present

**Comment by scholokov** [comment]
please retest

**Comment by MykhailoBorovikov** [comment]
verified
