### ISSUE TITLE
QA Программa - lesson "Тестирование за пределами требований" is missing

### ISSUE THREAD

**Issue by Tipaieva** [scholokov/qax-portal#116]
### Description:
In the QA Программе the lesson "Тестирование за пределами требований" (https://portal.qax-camp.com.ua/metro-retro/) is missing

### Steps:

1. Open site
2. Select QA Программa https://portal.qax-camp.com.ua/qa-program/

### Actual:
the lesson "Тестирование за пределами требований" **is missing**

### Expected:
the lesson "Тестирование за пределами требований" **is present**

### Environment:
Desctop/Wondows 10 Pro/ Google Chrome 96.0.4664.45 (64 bit)

### Attachment:
![image](https://user-images.githubusercontent.com/92110820/143770422-f91efbf5-bd18-4aef-a4b6-707c0ef0d241.png)

**Comment by GeorgiiZ90** [comment]
Fixed

**Comment by MykhailoBorovikov** [comment]
Verified
