### ISSUE TITLE
QA Программа - Course Особенности тестирования десктопных приложений - wrong author of the Course Content

### ISSUE THREAD

**Issue by Tipaieva** [scholokov/qax-portal#118]
### Discription:
At the end of the Course Content 'Особенности тестирования десктопных приложений" marked wrong author of the Course Content

### Steps:

1. Open site
2. Select "QA Программа" - "Особенности тестирования десктопных приложений" (https://portal.qax-camp.com.ua/courses/%d0%be%d1%81%d0%be%d0%b1%d0%b5%d0%bd%d0%bd%d0%be%d1%81%d1%82%d0%b8-%d1%82%d0%b5%d1%81%d1%82%d0%b8%d1%80%d0%be%d0%b2%d0%b0%d0%bd%d0%b8%d1%8f-%d0%b4%d0%b5%d1%81%d0%ba%d1%82%d0%be%d0%bf%d0%bd%d1%8b%d1%85/)
3. Scroll down to the author of the Course Content

### Actual:
**Denis Scholokov** is marked as the author of the Course Content

### Expected:
**Rudchenko Yuliya** is marked as the author of the Course Content

### Environment:
Decktop/ Windows 10 Pro/ Google Chrome 96.0.4664.45 (64 bit)

### Attachment:
![image](https://user-images.githubusercontent.com/92110820/143856603-eb56339c-78e8-4304-8eba-cfe92d372c33.png)

**Comment by scholokov** [comment]
fixed

**Comment by Tipaieva** [comment]
verified
