### ISSUE TITLE
QA Программa - lesson "Обучение – это привычка! – Андрей Курпатов" is missing

### ISSUE THREAD

**Issue by Tipaieva** [scholokov/qax-portal#119]
### Description:
In the QA Программа the lesson "Обучение – это привычка! – Андрей Курпатов" (https://portal.qax-camp.com.ua/%d0%be%d0%b1%d1%83%d1%87%d0%b5%d0%bd%d0%b8%d0%b5-%d1%8d%d1%82%d0%be-%d0%bf%d1%80%d0%b8%d0%b2%d1%8b%d1%87%d0%ba%d0%b0-%d0%b0%d0%bd%d0%b4%d1%80%d0%b5%d0%b9-%d0%ba%d1%83%d1%80%d0%bf%d0%b0/) is missing

### Steps:
1. Open site
2. Select QA Программa https://portal.qax-camp.com.ua/qa-program/

### Actual:
the lesson "Обучение – это привычка! – Андрей Курпатов" **is missing**

### Expected:
the lesson "Обучение – это привычка! – Андрей Курпатов" **is present**

### Environment:
Desctop/Wondows 10 Pro/ Google Chrome 96.0.4664.45 (64 bit)

### Attachment:
![image](https://user-images.githubusercontent.com/92110820/143860207-1a2cbd49-4528-4929-bfe1-cbab56d7e782.png)

**Comment by scholokov** [comment]
добавлен урок
Обучение – это привычка! – Андрей Курпатов
в курс
Обучение – это привычка! – Андрей Курпатов
блок
Soft Skills development

**Comment by MykhailoBorovikov** [comment]
Verified
