### ISSUE TITLE
QA Программа - lesson "Art Of Leadership" - is missing

### ISSUE THREAD

**Issue by Tipaieva** [scholokov/qax-portal#120]
### Description:
In the QA Программа the lesson "Art Of Leadership" (https://portal.qax-camp.com.ua/art-of-leadership/) is missing

### Steps:
1. Open site
2. Select QA Программa https://portal.qax-camp.com.ua/qa-program/

### Actual:
the lesson "Art Of Leadership" **is missing**

### Expected:
the lesson "Art Of Leadership" **is present**

### Environment:
Desctop/Wondows 10 Pro/ Google Chrome 96.0.4664.45 (64 bit)

### Attachment:
![6OufzpYAmN](https://user-images.githubusercontent.com/92110820/143861742-f3170c38-5957-4695-8e05-5e27e87184c7.gif)

**Comment by scholokov** [comment]
добавлен урок
Art Of Leadership
курс
Art Of Leadership
блок
Soft Skills development

**Comment by Tipaieva** [comment]
Verified
