### ISSUE TITLE
QA Программа - course "Составление резюме (CV)" is missing

### ISSUE THREAD

**Issue by Tipaieva** [scholokov/qax-portal#125]
### Description:
In the QA Программа the course "Составление резюме (CV)" (https://portal.qax-camp.com.ua/cv/) is missing

### Steps:
1. Open site
2. Select QA Программa https://portal.qax-camp.com.ua/qa-program/

### Actual:
the course "Составление резюме (CV)" **is missing**

### Expected:
the course "Составление резюме (CV)" **is present**

### Environment:
Desctop/Wondows 10 Pro/ Google Chrome 96.0.4664.45 (64 bit)

### Attachment:
![RIXFUtmPHQ](https://user-images.githubusercontent.com/92110820/143910198-88621b5b-160b-4772-b28e-fe20b14f694e.png)

**Comment by scholokov** [comment]
создан урок и добавлен контент
Составление резюме (CV) from the Tech Side
добавлен курс
Составление резюме (CV)
блок
HR

**Comment by Tipaieva** [comment]
verified
