### ISSUE TITLE
QA Программа - course "Как пройти собеседование" is missing

### ISSUE THREAD

**Issue by Tipaieva** [scholokov/qax-portal#126]
### Description:
In the QA Программа the course "Как пройти собеседование" (https://portal.qax-camp.com.ua/interview/) is missing

### Steps:
1. Open site
2. Select QA Программa https://portal.qax-camp.com.ua/qa-program/

### Actual:
the course "Как пройти собеседование" **is missing**

### Expected:
the course "Как пройти собеседование" **is present**

### Environment:
Desctop/Wondows 10 Pro/ Google Chrome 96.0.4664.45 (64 bit)

### Attachment:
![s2X6EpTRVX](https://user-images.githubusercontent.com/92110820/143911290-4406e63f-4109-4e80-bde3-ccd32e6243b6.gif)

**Comment by scholokov** [comment]
fixed

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by MykhailoBorovikov** [comment]
Verified
