### ISSUE TITLE
Cource "Обучение – это привычка! – Андрей Курпатов" - content of the cource is missing

### ISSUE THREAD

**Issue by Tipaieva** [scholokov/qax-portal#127]
### Description:
In the cource "Обучение – это привычка! – Андрей Курпатов" the content. namely the video lesson "Мозг и привычки. Андрей Курпатов отвечает на вопросы подписчиков", of the cource is missing.

### Steps:
1. Open site
2. Select QA - QA Программa - Обучение – это привычка! – Андрей Курпатов (https://portal.qax-camp.com.ua/courses/%d0%be%d0%b1%d1%83%d1%87%d0%b5%d0%bd%d0%b8%d0%b5-%d1%8d%d1%82%d0%be-%d0%bf%d1%80%d0%b8%d0%b2%d1%8b%d1%87%d0%ba%d0%b0-%d0%b0%d0%bd%d0%b4%d1%80%d0%b5%d0%b9-%d0%ba%d1%83%d1%80%d0%bf/)

### Actual:
content, namely the video lesson "Мозг и привычки. Андрей Курпатов отвечает на вопросы подписчиков", of the cource is **missing**

### Expected:
content, namely the video lesson "Мозг и привычки. Андрей Курпатов отвечает на вопросы подписчиков", of the cource **is present**

### Environment:
Desctop/Wondows 10 Pro/ Google Chrome 96.0.4664.45 (64 bit)

### Attachment:
![31vxl1WhqC](https://user-images.githubusercontent.com/92110820/144057132-0451f838-af08-4d41-abdf-4feb5a88ccb4.png)

**Comment by scholokov** [comment]
fixed

**Comment by MykhailoBorovikov** [comment]
Verified
