### ISSUE TITLE
Cource HR: lesson HR – Вопросы-Ответы - lesson contain is not found, error 404 is displyed

### ISSUE THREAD

**Issue by Tipaieva** [scholokov/qax-portal#129]
### Description:
In the lesson HR – Вопросы-Ответы lesson contain is not found, error 404 is displyed.
 
### Steps:
1. Open site
2. Select QA - HR - HR – Вопросы-Ответы (https://portal.qax-camp.com.ua/hr-denis/)

### Actual:
**lesson contain is not found, error 404 is displyed** in the lesson HR – Вопросы-Ответы

### Expected:
**lesson content is displayed without errors** in the lesson HR – Вопросы-Ответы

### Environment:
Desctop/Wondows 10 Pro/ Google Chrome 96.0.4664.45 (64 bit)

### Attachment:
![image](https://user-images.githubusercontent.com/92110820/144214267-b3b0d13d-427a-4899-b311-a1d8ef49184d.png)

**Comment by MykhailoBorovikov** [comment]
issue is still present

**Comment by scholokov** [comment]
duplicate
