### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by Eugen-Ts** [scholokov/qax-portal#14]
Show the portal to the designer - tell / describe his opinion, recommendations

**Comment by etaranyuk** [comment]
Need to test disighn -  https://www.figma.com/file/UyTNSS6KCOdphdTev1HrLF/Untitled?node-id=0%3A1

**Comment by Olesya0518** [comment]
@scholokov  @Eugen-Ts @etaranyuk 
Check the results of all logs at the top after changing the font sizes in devtools.

size: 64mp is too large and overlaps sections in the header.
https://github.com/scholokov/qax-portal/blob/Olesya0518-(QA)/Screenshot_92_LI.jpg

size: 42mp-visually spoils the logs, too many lines to read.
https://github.com/scholokov/qax-portal/blob/Olesya0518-(QA)/Screenshot_95_LI.jpg

size: 36mp is nice to look at and is best suited for a title.
https://github.com/scholokov/qax-portal/blob/Olesya0518-(QA)/Screenshot_93_LI.jpg
