### ISSUE TITLE
Create lesson "Тестировщик. Кто это" in block "Entry level"

### ISSUE THREAD

**Issue by Eugen-Ts** [scholokov/qax-portal#141]
pls create lesson "Тестировщик. Кто это" in block "Entry level"
https://portal.qax-camp.com.ua/courses/%d0%b2%d0%b2%d0%b5%d0%b4%d0%b5%d0%bd%d0%b8%d0%b5-%d0%b2-%d1%82%d0%b5%d1%81%d1%82%d0%b8%d1%80%d0%be%d0%b2%d0%b0%d0%bd%d0%b8%d0%b5-%d0%bf%d0%be/lessons/qawhoarethey/

**Comment by MykhailoBorovikov** [comment]
Verified
