### ISSUE TITLE
Create course "Особенности тестирования десктопных приложений"

### ISSUE THREAD

**Issue by Eugen-Ts** [scholokov/qax-portal#143]
pls create course "Особенности тестирования десктопных приложений"
https://portal.qax-camp.com.ua/courses/%d0%be%d1%81%d0%be%d0%b1%d0%b5%d0%bd%d0%bd%d0%be%d1%81%d1%82%d0%b8-%d1%82%d0%b5%d1%81%d1%82%d0%b8%d1%80%d0%be%d0%b2%d0%b0%d0%bd%d0%b8%d1%8f-%d0%b4%d0%b5%d1%81%d0%ba%d1%82%d0%be%d0%bf%d0%bd%d1%8b%d1%85/

**Comment by MykhailoBorovikov** [comment]
Verified
