### ISSUE TITLE
Create lesson "Особенности тестирования десктопных приложений" in block "Особенности тестирования на различных платформах"

### ISSUE THREAD

**Issue by Eugen-Ts** [scholokov/qax-portal#144]
pls Create lesson "Особенности тестирования десктопных приложений" in block "Особенности тестирования на различных платформах"
https://portal.qax-camp.com.ua/courses/%d0%be%d1%81%d0%be%d0%b1%d0%b5%d0%bd%d0%bd%d0%be%d1%81%d1%82%d0%b8-%d1%82%d0%b5%d1%81%d1%82%d0%b8%d1%80%d0%be%d0%b2%d0%b0%d0%bd%d0%b8%d1%8f-%d0%b4%d0%b5%d1%81%d0%ba%d1%82%d0%be%d0%bf%d0%bd%d1%8b%d1%85/lessons/desktopapptesting/

**Comment by MykhailoBorovikov** [comment]
Verified
