### ISSUE TITLE
Create course and lesson "Книга: Святослав Куликов – Тестирование Программного Обеспечения" in block "Entry level"

### ISSUE THREAD

**Issue by Eugen-Ts** [scholokov/qax-portal#146]
Pls create course and lesson "Книга: Святослав Куликов – Тестирование Программного Обеспечения" in block "Entry level"
and need to add labels "Дополнительный материал"
https://portal.qax-camp.com.ua/courses/%d0%ba%d0%bd%d0%b8%d0%b3%d0%b0-%d1%81%d0%b2%d1%8f%d1%82%d0%be%d1%81%d0%bb%d0%b0%d0%b2-%d0%ba%d1%83%d0%bb%d0%b8%d0%ba%d0%be%d0%b2-%d1%82%d0%b5%d1%81%d1%82%d0%b8%d1%80%d0%be%d0%b2%d0%b0%d0%bd/

**Comment by MykhailoBorovikov** [comment]
Verified
