### ISSUE TITLE
Create lesson "Обучение – это привычка! – Андрей Курпатов"

### ISSUE THREAD

**Issue by Eugen-Ts** [scholokov/qax-portal#148]
Create lesson "Обучение – это привычка! – Андрей Курпатов" in block "Soft Skills development"
https://portal.qax-camp.com.ua/%d0%be%d0%b1%d1%83%d1%87%d0%b5%d0%bd%d0%b8%d0%b5-%d1%8d%d1%82%d0%be-%d0%bf%d1%80%d0%b8%d0%b2%d1%8b%d1%87%d0%ba%d0%b0-%d0%b0%d0%bd%d0%b4%d1%80%d0%b5%d0%b9-%d0%ba%d1%83%d1%80%d0%bf%d0%b0/

**Comment by Eugen-Ts** [comment]
Не создан блок Soft Skills development
@scholokov

**Comment by MykhailoBorovikov** [comment]
VErified
![Screenshot_49](https://user-images.githubusercontent.com/104158199/168421882-e031124e-70aa-48c5-be29-157d4d35fefe.png)
