### ISSUE TITLE
Create lesson "Art Of Leadership"

### ISSUE THREAD

**Issue by Eugen-Ts** [scholokov/qax-portal#149]
Create lesson "Art Of Leadership" in block "Soft Skills development"
https://portal.qax-camp.com.ua/art-of-leadership/

**Comment by Eugen-Ts** [comment]
Не перенесен на уровень урока
@scholokov

**Comment by MykhailoBorovikov** [comment]
Verified
![Screenshot_48](https://user-images.githubusercontent.com/104158199/168420544-ed91e751-1a2d-4d66-838e-ada44740a4f9.png)
