### ISSUE TITLE
Create lesson "Веселое выступление о необычных дизайнах продуктов"

### ISSUE THREAD

**Issue by Eugen-Ts** [scholokov/qax-portal#151]
Create lesson "Веселое выступление о необычных дизайнах продуктов" in block "Web, Mobile, UI – Testing"
And add label "необязателен, для прохождения"
https://portal.qax-camp.com.ua/courses/ui/lessons/%d0%b2%d0%b5%d1%81%d0%b5%d0%bb%d0%be%d0%b5-%d0%b2%d1%8b%d1%81%d1%82%d1%83%d0%bf%d0%bb%d0%b5%d0%bd%d0%b8%d0%b5-%d0%be-%d0%bd%d0%b5%d0%be%d0%b1%d1%8b%d1%87%d0%bd%d1%8b%d1%85-%d0%b4%d0%b8%d0%b7%d0%b0/

**Comment by MykhailoBorovikov** [comment]
VErified
