### ISSUE TITLE
Prepare a test plan

### ISSUE THREAD

**Issue by Eugen-Ts** [scholokov/qax-portal#16]
Prepare a test plan for testing the portal: https://portal.qax-camp.com.ua/

**Comment by Olesya0518** [comment]
@scholokov Link to test plan

https://docs.google.com/document/d/13oPwQjffZwLPqn8e4w7mBH2Pc8MCc1EV/edit?usp=sharing&ouid=113831790160201899738&rtpof=true&sd=true
