### ISSUE TITLE
Create lesson "Scrum и XP – Заметки с передовой – Хенрик Книберг"

### ISSUE THREAD

**Issue by Eugen-Ts** [scholokov/qax-portal#160]
Create lesson "Scrum и XP – Заметки с передовой – Хенрик Книберг" in block "Agile / SCRUM"
https://portal.qax-camp.com.ua/courses/agile-scrum/lessons/scrum-%d0%b8-xp-%d0%b7%d0%b0%d0%bc%d0%b5%d1%82%d0%ba%d0%b8-%d1%81-%d0%bf%d0%b5%d1%80%d0%b5%d0%b4%d0%be%d0%b2%d0%be%d0%b9-%d1%85%d0%b5%d0%bd%d1%80%d0%b8%d0%ba-%d0%ba%d0%bd%d0%b8%d0%b1%d0%b5%d1%80/

**Comment by MykhailoBorovikov** [comment]
Verified
