### ISSUE TITLE
Create lesson "Test Plan vs Test Strategy"

### ISSUE THREAD

**Issue by Eugen-Ts** [scholokov/qax-portal#163]
Create lesson "Test Plan vs Test Strategy" in block "Теория тестирования"
https://portal.qax-camp.com.ua/courses/scrum-%d0%b8-kanban-%d0%b2%d1%8b%d0%b6%d0%b8%d0%bc%d0%b0%d0%b5%d0%bc-%d0%bc%d0%b0%d0%ba%d1%81%d0%b8%d0%bc%d1%83%d0%bc-%d1%85%d0%b5%d0%bd%d1%80%d0%b8%d0%ba-%d0%ba%d0%bd%d0%b8%d0%b1/

**Comment by MykhailoBorovikov** [comment]
Verified
