### ISSUE TITLE
Lesson's url (PM Program) contains russian language.

### ISSUE THREAD

**Issue by Korchenok** [scholokov/qax-portal#165]
Discription:

Web-site url contains russian language:
https://portal.qax-camp.com.ua/pm-%d0%bf%d1%80%d0%be%d0%b3%d1%80%d0%b0%d0%bc%d0%bc%d0%b0/

Steps:
1. Open portal.qax-camp.com.ua
2. Go to "Program", "PM Program"

![image](https://user-images.githubusercontent.com/91203038/153020537-79bae7f5-f530-40d8-b6e1-316cf61f147f.png)

Actual:
1. Web-site url contains russian language.

Expected:
1. Web-site url contains only English language. 

Environment:
Windows 10, Google Chrome 95.0.4638.69

**Comment by scholokov** [comment]
1. неуникализированный тайтл. в данном случае ты говоришь про страницу с курсом ПМ. а про это не упомянуто в тайтле

1.а. в тайтле не указана конкретная проблема. в каждом баге - что то некорректно

**Comment by scholokov** [comment]
2. Expected:
Web-site url is correct and contains only English language.

что значит фраза "Web-site url is correct" в данном контексте?

вторая половина очень конкретна. первая половина вообще непонятно о чем

**Comment by scholokov** [comment]
3. на скрине есть смысл сделать отметку, что бы не терять время на поиск нужного

**Comment by scholokov** [comment]
fixed

**Comment by MykhailoBorovikov** [comment]
verification failed

**Comment by scholokov** [comment]
verification failed

так не должно быть
вариант: та же самая ошибка существует: issue still exist

хотя бы немного не та: открываем новую, в старом пишем - закрываем в связи с открытием новой

**Comment by MykhailoBorovikov** [comment]
issue still exist

**Comment by scholokov** [comment]
fixed

**Comment by MykhailoBorovikov** [comment]
Verified
