### ISSUE TITLE
Lesson's url (QA Program) contains russian language

### ISSUE THREAD

**Issue by Korchenok** [scholokov/qax-portal#171]
Discription:

Web-site url contains russian language:
https://portal.qax-camp.com.ua/courses/sql/lessons/%d0%b1%d0%b0%d0%b7%d1%8b-%d0%b4%d0%b0%d0%bd%d0%bd%d1%8b%d1%85-%d1%87%d1%82%d0%be-%d1%8d%d1%82%d0%be-%d1%82%d0%b0%d0%ba%d0%be%d0%b5-%d0%b8-%d1%81-%d1%87%d0%b5%d0%bc-%d0%b8%d1%85-%d0%b5%d0%b4%d1%8f/

Steps:

Open portal.qax-camp.com.ua
Go to "Program", "QA Program", "Data bases, SQL"

![image](https://user-images.githubusercontent.com/91203038/153021828-1e90b735-f190-4899-8b26-557a62061a5b.png)

Actual:

Web-site url contains russian language.
Expected:

Web-site url contains only English language.
Environment:
Windows 10, Google Chrome 95.0.4638.69

**Comment by Korchenok** [comment]
https://github.com/scholokov/qax-portal/issues/102

**Comment by scholokov** [comment]
fixed

**Comment by MykhailoBorovikov** [comment]
verified
