### ISSUE TITLE
Home - Body - Видны надписи [raw] и [/raw] (Android)

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal#173]
Шаги воспроизведения:
1) Перейти в тестовую среду:
     https://qax-camp.com.ua/test-portal
2) Зарегистрироватся/войти в аккаунт
3) Перейти в вкладку "Home"
4) Посмотреть в левый верхний угол первого, и левый нижний угол последнего прогруженного сообщения в столбце "Latest Posts"

Ожидаемый результат:
Надписей [raw] и [/raw] не видно

Фактический результат:
Надписи [raw] и [/raw] видно

Операционная система:
Android, 8.1.0

Браузер:
Chrome

![Screenshot_20220406-163304_1](https://user-images.githubusercontent.com/95171672/162224885-a391a04f-4e0d-411f-8a9c-2041c3f9a9ff.jpg)
![Screenshot_20220406-163250_1](https://user-images.githubusercontent.com/95171672/162225061-fc71efa0-1c6d-4e91-818c-943252788194.jpg)

**Comment by scholokov** [comment]
дубликат
