### ISSUE TITLE
 Course - Zephyr Scale (TM4J) - No access to the content without registration on course

### ISSUE THREAD

**Issue by NataliaKutashenko** [scholokov/qax-portal#175]
Zephyr Scale (TM4J) course requests access to the content on a site [portal.qax-camp.com.ua](http://portal.qax-camp.com.ua/).
No access to the content without previous registration on Zephyr Scale (TM4J) course.

Steps to reproduce:

1. Open the site https://portal.qax-camp.com.ua/courses/zephyr-scale-tm4j/

2. Try to open the lesson from the course content.

Actual result:

“You currently don’t have access to this content” message has appeared. 

The User can't open Zephyr Scale (TM4J) course without previous registration on the course.

Expected result:

The  User doesn't need to be registered on Zephyr Scale (TM4J) course.

Environment:
Desktop/Macbook pro/ MacOS Monterey 12.2.1/ Chrome 98.0.4758.102

**Comment by scholokov** [comment]
The QAX Camp User opens Zephyr Scale (TM4J) course with access requirements and can’t use all the course content without course registration.

общая непонятная фраза. должен присутствовать четкий критерий

**Comment by scholokov** [comment]
нет экспектид результата

**Comment by scholokov** [comment]
лучше начитать с того "где" в тайтле

**Comment by scholokov** [comment]
for logged-in QAX Camp users.

вообще фраза непонятная

**Comment by scholokov** [comment]
Click the lesson from the course content.



try to open

**Comment by scholokov** [comment]
message has been received.

кем получена?
appeared

**Comment by NataliaKutashenko** [comment]
> нет экспектид результата

- исправлено.

**Comment by NataliaKutashenko** [comment]
> message has been received.
> 
> кем получена? appeared

- исправлено.

**Comment by NataliaKutashenko** [comment]
> Click the lesson from the course content.
> 
> try to open

-исправлено.

**Comment by NataliaKutashenko** [comment]
> for logged-in QAX Camp users.
> 
> вообще фраза непонятная

исправлено на "sign up"

**Comment by NataliaKutashenko** [comment]
> The QAX Camp User opens Zephyr Scale (TM4J) course with access requirements and can’t use all the course content without course registration.
> 
> общая непонятная фраза. должен присутствовать четкий критерий

-перефразировала предложение.

**Comment by NataliaKutashenko** [comment]
> лучше начитать с того "где" в тайтле

-

**Comment by scholokov** [comment]
а тайтл править?

**Comment by scholokov** [comment]
fixed

**Comment by GeorgiiZ90** [comment]
Fixed

**Comment by MykhailoBorovikov** [comment]
Verified
