### ISSUE TITLE
Program - QA Program - Course - Роли и артефакты в проектной команде - table of contents "Заказчик" wrong url

### ISSUE THREAD

**Issue by MykhailoBorovikov** [scholokov/qax-portal#179]
Precondition: Be logged in

Steps to reproduce:

1) Open portal.qax-camp.com.ua
2) Open a tab Program on the navigation menu - QA Program - Роли и артефакты в проектной команде 
3) Open course content "Роли и артефакты в проектной команде" - <a href="https://portal.qax-camp.com.ua/courses/project-team/lessons/roles-in-team/">Роли и артефакты в проектной команде </a>
4) Pay attention on "Заказчик" link at contents table

Actual result:

Link contains wrong URL: https://portal.qax-camp.com.ua/project-team/#customer 

Expected result:

Link contains wright URL: https://portal.qax-camp.com.ua/courses/project-team/lessons/roles-in-team/#customer

![Screenshot_9](https://user-images.githubusercontent.com/104158199/164913192-def36e59-460e-4626-8428-1f90c7b2b6bc.png)

**Comment by scholokov** [comment]
нумерация шагов

**Comment by scholokov** [comment]
![image](https://user-images.githubusercontent.com/22824947/164886744-027e0e06-1a89-48be-b883-db177dfa5de4.png)
в тайтле какая то непонятная переадресация
в экшуал/экспектид уже про неправильную линку

**Comment by scholokov** [comment]
еще удобнее давать прямую линку на статью в шагах

**Comment by scholokov** [comment]
асайним на меня+себя+ПМ

**Comment by scholokov** [comment]
лейба - bug

**Comment by scholokov** [comment]
проект - Bugs by QA Direction

**Comment by scholokov** [comment]
статус - после создания - не меняем

**Comment by scholokov** [comment]
я возвращаю обратно со статусом нид мор инфо, после исправления - мне в статусе нью

**Comment by scholokov** [comment]
чисто технически тут открывать линку необязательно
вместо 4 шага можно указывать "обратить внимание на URL "Заказчик" в блоке contents table

**Comment by scholokov** [comment]
на скрине неудачный подбор зеленого цвета. сливается с тулбаром

**Comment by scholokov** [comment]
с учетом что линка длинная есть смысл выделить в чем разница.
иначе можно не пойти в детали и не увидеть разницу

**Comment by MykhailoBorovikov** [comment]
issue is still present

**Comment by GeorgiiZ90** [comment]
Fixed

**Comment by MykhailoBorovikov** [comment]
> Fixed

issue is still present

**Comment by scholokov** [comment]
fixed

**Comment by MykhailoBorovikov** [comment]
verified
