### ISSUE TITLE
QA Program - курс Zephyr Scale - Неверное расположение ссылок на следующий и предыдущий уроки (PC)

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal#184]
Описание:
В нижней части каждого урока в курсе, ссылки на предыдущий и следующий уроки перепутаны местами, но сами ссылки работают правильно 

Шаги воспроизведения:
1.Перейти в тестовую среду: https://qax-camp.com.ua/test-portal
2.Зарегистрироватся/войти в тестовый аккаунт
3.Открыть любой урок курса Zephyr Scale (Маршрут: Program -> QA Program -> Zephyr Scale (TM4J) -> Zephyr Scale – 1. Folders Structure: Tests)
4.Опустится в низ страницы и обратить внимание на ссылки надписями"PREVIOUS" и "NEXT"

Ожидаемый результат:
Под надписью "NEXT" находится ссылка на следующий урок, под надписью "PREVIOUS" - на предыдущий 

Фактический результат:
Под надписью "NEXT" находится ссылка на предыдущий урок, под надписью "PREVIOUS" - на следующий

Устройство и операционная система:
Lenovo Ideapad Z500, Windows 10

Браузер:
Chrome

![Zephyr Scale – 1  Folders Structure_ Tests – QAX Camp - Google Chrome 26 04 2022 17_05_34_LI](https://user-images.githubusercontent.com/95171672/165319537-a87585d5-dbdd-4785-8783-7e9d33c0771a.jpg)
![Zephyr Scale (TM4J) – QAX Camp - Google Chrome 26 04 2022 17_03_03](https://user-images.githubusercontent.com/95171672/165319565-e4615d6e-e4e4-4702-b2f1-1313a5bda8b6.png)

**Comment by scholokov** [comment]
проблема не до конца исследована
