### ISSUE TITLE
Topics - Programs - MetroRetro - MetroRetro lesson is not linked to lesson page

### ISSUE THREAD

**Issue by MykhailoBorovikov** [scholokov/qax-portal#203]
Description:

MetroRetro lesson is not linked to course page - https://portal.qax-camp.com.ua/courses/metro-retro/

Preconditions: be logged in

Steps to reproduce:

1) Open "Topics" - "Programs"
2) Open "MetroRetro"
3) Scroll down and see that lesson is missing

Actual result: 
Lesson is not linked to course page

Expected result: 
Lesson is linked to course page

![Screenshot_2](https://user-images.githubusercontent.com/104158199/165537089-8d500250-8e08-4b37-812d-8e08a08f9440.png)

**Comment by scholokov** [comment]
недоисследована проблема:
сам урок существует, но он не привязан к курсу
само описание можно понять как сам урок не существует, по крайней мере описание этого не исключает
https://portal.qax-camp.com.ua/lessons/metro-retro/

**Comment by MykhailoBorovikov** [comment]
> недоисследована проблема: сам урок существует, но он не привязан к курсу само описание можно понять как сам урок не существует, по крайней мере описание этого не исключает https://portal.qax-camp.com.ua/lessons/metro-retro/

Описание подправлю. Но что за ссылка? Она редиректит меня на архив.

**Comment by scholokov** [comment]
у меня нормально она открывается

**Comment by MykhailoBorovikov** [comment]
> у меня нормально она открывается

у меня URL [https://portal.qax-camp.com.ua/lessons/](https://portal.qax-camp.com.ua/lessons/metro-retro/) выдает 404 ошибку, а попытка перейти по ссылке с уроком - редирект по 302 коду.

**Comment by scholokov** [comment]
This is not duplicate of https://github.com/scholokov/qax-portal/issues/115 There is different url of lesson
это в баге не ппишут

**Comment by MykhailoBorovikov** [comment]
> This is not duplicate of #115 There is different url of lesson это в баге не ппишут

подчистил

**Comment by GeorgiiZ90** [comment]
Fixed

**Comment by MykhailoBorovikov** [comment]
Verified
