### ISSUE TITLE
PM Program - Github:  Endless redirection when click on lesson 'Github - Development Flow'

### ISSUE THREAD

**Issue by MykhailoBorovikov** [scholokov/qax-portal#205]
**Preconditions:** be logged in

**STR:**

1) Go to Program - PM Program
2) Scroll down
2) Open GitHub course
3) Click on 'Github - <a href="https://portal.qax-camp.com.ua/topic/github-development-flow/">'Github - Development Flow' </a>

**Result:**
Endless redirection when click on lesson <a href="https://portal.qax-camp.com.ua/topic/github-development-flow/">'Github - Development Flow' </a>

**Expected result:**
Lesson 'Github - Development Flow' will open 
![Screenshot_6](https://user-images.githubusercontent.com/104158199/165779909-72924dbd-ea98-4f0b-babd-660ac71bbf95.png)

**Comment by scholokov** [comment]
please retest

**Comment by MykhailoBorovikov** [comment]
Issue is still present
![Screenshot_3](https://user-images.githubusercontent.com/104158199/166308984-e9f6149a-91b9-4422-9b3d-6b5ab5193363.png)

**Comment by scholokov** [comment]
Scroll down and open GitHub course

у тебя два шага в одном шаге. из-за этого не мог воспроизвести ошибку, так низя делать:
т.е. я читаю начало строки - скрол и дальше не читаю. а у тебя там опен

**Comment by MykhailoBorovikov** [comment]
> Scroll down and open GitHub course
> 
> у тебя два шага в одном шаге. из-за этого не мог воспроизвести ошибку, так низя делать: т.е. я читаю начало строки - скрол и дальше не читаю. а у тебя там опен

исправился

**Comment by scholokov** [comment]
Result:
Endless redirection when click on lesson ['Github - Development Flow'](https://portal.qax-camp.com.ua/topic/github-development-flow/)

у тебя тут присутствует линка. ошибка именно на ней? если на ней то стоит ее в шаги запихнуть

**Comment by MykhailoBorovikov** [comment]
> Result: Endless redirection when click on lesson ['Github - Development Flow'](https://portal.qax-camp.com.ua/topic/github-development-flow/)
> 
> у тебя тут присутствует линка. ошибка именно на ней? если на ней то стоит ее в шаги запихнуть

исправил

**Comment by scholokov** [comment]
у меня не воспроизводится. запиши плиз видео

**Comment by MykhailoBorovikov** [comment]
https://user-images.githubusercontent.com/104158199/166518465-4b8b92a1-c011-40e9-a2ee-9d1a9d17efe6.mp4

**Comment by scholokov** [comment]
из видео ничего непонятно
надо фокусировать человека на определенных действиях. например подводя мышку к обекту и делая круговые движения перед нажатием. иначе непонятно что ты нажимаешь.
другой вариант - использовать приложения для захвата видео, где можно включить фокус на курсоре

**Comment by MykhailoBorovikov** [comment]
версия 2.0, дополненная и исправленная
https://user-images.githubusercontent.com/104158199/166675948-24d3aecb-57f8-4903-8835-7290351ac20e.mp4

**Comment by scholokov** [comment]
видео хорошее
можешь еще кого то попросить проверить у себя?
так же можно эту же проблему попробовать воспроизвести на мобильном
еще на той же системе, но перед этим почистить кэш и куки

**Comment by MykhailoBorovikov** [comment]
> видео хорошее можешь еще кого то попросить проверить у себя? так же можно эту же проблему попробовать воспроизвести на мобильном еще на той же системе, но перед этим почистить кэш и куки

я после обнаружения проблемы успел переустановить систему начисто. проблема осталась.
на телефоне проблема такая же


https://user-images.githubusercontent.com/104158199/166683828-57b2b044-76d6-4e10-ba86-ef038c91c42e.mp4

**Comment by MykhailoBorovikov** [comment]
The bug is no longer relevant

**Comment by scholokov** [comment]
если не релевантный - то забирай себе и клозаай
