### ISSUE TITLE
PM-Program - Как пройти собеседование - From HR Side: Wrong author of lesson

### ISSUE THREAD

**Issue by MykhailoBorovikov** [scholokov/qax-portal#207]
Wrong author of lesson: <a href="https://portal.qax-camp.com.ua/courses/passing-interview/lessons/interview-from-hr-side/">From HR Side</a>

**Precondition:** be logged in

**STR:** 
1)Open Program - PM Program
2) Scroll down to HR section
3) Open course "Как пройти собеседование"
4) Open lesson "From HR Side"
5) Scroll  down to author

**Actual:**

Author is Denis Scholokov

**Expected:** Author is Ольга Компанець
![Screenshot_12](https://user-images.githubusercontent.com/104158199/166814882-904d2812-bccd-4ff7-bc4e-0dc38a779c37.png)

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by MykhailoBorovikov** [comment]
issue is still present

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by MykhailoBorovikov** [comment]
Verified
