### ISSUE TITLE
PM Program - LinkedIn – как выжать максимум (для поиска вакансий): Wrong author of lesson

### ISSUE THREAD

**Issue by MykhailoBorovikov** [scholokov/qax-portal#208]
Wrong author of lesson: <a href="https://portal.qax-camp.com.ua/courses/linkedin/lessons/linkedin/">LinkedIn – как выжать максимум (для поиска вакансий)</a>

**Precondition:** be logged in

**STR:** 
1)Open Program - PM Program
2) Scroll down to HR section
3) Open course "Как пройти собеседование"
4) Open lesson "LinkedIn – как выжать максимум (для поиска вакансий)"
5) Scroll  down to author

**Actual:**

Author is Denis Scholokov

**Expected:** Author is Daria Kazarinova

![Screenshot_13](https://user-images.githubusercontent.com/104158199/166819475-d03e54a3-7a04-40d9-80c6-2d1aeffdb1cc.png)

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by MykhailoBorovikov** [comment]
Verified
