### ISSUE TITLE
QA Program - QA Basics - Дополнительные материалы- "Книга: Святослав Куликов - Тестирование Программного Обеспечения": URL contains invalid characters

### ISSUE THREAD

**Issue by MykhailoBorovikov** [scholokov/qax-portal#209]
URL contains invalid characters -  <a href="https://portal.qax-camp.com.ua/courses/book-kulikov/lessons/%d1%81%d0%b2%d1%8f%d1%82%d0%be%d1%81%d0%bb%d0%b0%d0%b2-%d0%ba%d1%83%d0%bb%d0%b8%d0%ba%d0%be%d0%b2-%d1%82%d0%b5%d1%81%d1%82%d0%b8%d1%80%d0%be%d0%b2%d0%b0%d0%bd%d0%b8%d0%b5-%d0%bf%d1%80%d0%be%d0%b3/">Книга: Святослав Куликов - Тестирование Программного Обеспечения</a>

**Preconditions:** 
Be logged in

**STR:**

1) Open Program - QA Program - QA Basics
2) Scroll down to "Дополнительные материалы"
3) 

Open "Книга: Святослав Куликов - Тестирование Программного Обеспечения"

**Actual:**

URL contains invalid characters

**Expected:**

URL contains only english characters
![Screenshot_14](https://user-images.githubusercontent.com/104158199/166886102-95ae036e-6a5e-4cf1-b1e1-471d17a9b84c.png)

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by MykhailoBorovikov** [comment]
Verified
