### ISSUE TITLE
QA Program - QA Basics - Дополнительные материалы- "Книга: Роман Савин – Тестирование dot com": URL contains invalid characters

### ISSUE THREAD

**Issue by MykhailoBorovikov** [scholokov/qax-portal#210]
URL contains invalid characters -  <a href="https://portal.qax-camp.com.ua/courses/savin/lessons/%d1%80%d0%be%d0%bc%d0%b0%d0%bd-%d1%81%d0%b0%d0%b2%d0%b8%d0%bd-%d1%82%d0%b5%d1%81%d1%82%d0%b8%d1%80%d0%be%d0%b2%d0%b0%d0%bd%d0%b8%d0%b5-dot-com//">Книга: Роман Савин – Тестирование dot com</a>

**Preconditions:** 
Be logged in

**STR:**

1) Open Program - QA Program - QA Basics
2) Scroll down to "Дополнительные материалы"
3) Open "Книга: Роман Савин – Тестирование dot com"

**Actual:**

URL contains invalid characters

**Expected:**

URL contains only english characters
![Screenshot_15](https://user-images.githubusercontent.com/104158199/166886422-b1e1d90b-8832-4caf-b834-cd55def9d408.png)

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by MykhailoBorovikov** [comment]
Verified
