### ISSUE TITLE
Trainers page: missing info about trainer Олена Волохонська

### ISSUE THREAD

**Issue by MykhailoBorovikov** [scholokov/qax-portal#211]
#134
Missing info about trainer Олена Волохонська

Preconditions: be loged in

STR:
1) Open https://portal.qax-camp.com.ua/trainers/
2) Scroll down
3) Check out on last trainer

Actual:

Last trainer is Дарія Казарінова

Expected: 

Last trainer is Олена Волохонська
![Screenshot_16](https://user-images.githubusercontent.com/104158199/167247953-c94b6bf3-666c-4d4b-9c24-92dc8e877a01.png)

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by MykhailoBorovikov** [comment]
Verified
