### ISSUE TITLE
QA Program - HR - Cоставление резюме(СV) - Cоставление резюме(СV)-From HR Side: no access to еducational material

### ISSUE THREAD

**Issue by MykhailoBorovikov** [scholokov/qax-portal#212]
No access to educational material (https://portal.qax-camp.com.ua/courses/cv/lessons/cv-hr/)

**Preconditions:**
Be logged in

**STR:**
1) Open Program - QA Program
2) Scroll to hr block
3) Open Cоставление резюме(СV) course
4) Open Cоставление резюме(СV)-From HR Side lesson

**Actual:** 

No access to educational material

**Expected:** 

Accessible educational material

![Screenshot_17](https://user-images.githubusercontent.com/104158199/167248698-9d16ec3f-f235-408c-82ba-7b875be20dd8.png)

**Comment by scholokov** [comment]
fixed

**Comment by MykhailoBorovikov** [comment]
issue is till pres
![Screenshot_22](https://user-images.githubusercontent.com/104158199/167478649-fa2d1670-d490-4e14-81d6-a5191a971b87.png)
ent

**Comment by scholokov** [comment]
fixed

**Comment by MykhailoBorovikov** [comment]
issue is still present

**Comment by scholokov** [comment]
fixed

**Comment by MykhailoBorovikov** [comment]
Verified
