### ISSUE TITLE
Program - QA Program - Github: Wrong link to the lesson 'GitHub – How To Create Labels and Boards'

### ISSUE THREAD

**Issue by MykhailoBorovikov** [scholokov/qax-portal#214]
Wrong link to the lesson in course <a href="https://portal.qax-camp.com.ua/courses/github/">Github</a>

**Preconditions:** 
Be logged in

**STR:**
1) Open Program - QA Program
2) Scroll donw to Github
3) Open Github course
4) Click on 'GitHub – How To Create Labels and Boards'

**Actual:**
Link is wrong and lesson do not opens

**Expected:** 
Link is correct and lesson opens
![Screenshot_33](https://user-images.githubusercontent.com/104158199/168023130-c2fedc3f-7d4d-45d9-811b-c4bc313e3323.png)

**Comment by scholokov** [comment]
fixed

**Comment by MykhailoBorovikov** [comment]
Verified
