### ISSUE TITLE
Program - QA Program - Github: Wrong link to the lesson 'GitHub – Development flow'

### ISSUE THREAD

**Issue by MykhailoBorovikov** [scholokov/qax-portal#215]
Wrong link to the lesson in course [Github](https://portal.qax-camp.com.ua/courses/github/)

**Preconditions:**
Be logged in

**STR:**

1. Open Program - QA Program
2. Scroll donw to Github
3. Open Github course
4. Click on 'GitHub – Development flow'

**Actual:**
Link is wrong and lesson do not opens

**Expected:**
Link is correct and lesson opens
![Screenshot_32](https://user-images.githubusercontent.com/104158199/168022945-0936e5bf-c522-4a0a-95b1-803ca03bb9eb.png)

**Comment by scholokov** [comment]
fixed

**Comment by MykhailoBorovikov** [comment]
Verified
