### ISSUE TITLE
Program - QA Program - Github: Wrong link to the lesson 'GitHub – Actions'

### ISSUE THREAD

**Issue by MykhailoBorovikov** [scholokov/qax-portal#216]
**Preconditions:** 
Be logged in

**STR:**
1) Open Program - QA Program
2) Scroll donw to Github
3) Open Github course
4) Click on 'GitHub – Actions'

**Actual:**
Link is wrong and lesson do not opens

**Expected:** 
Link is correct and lesson opens
![Screenshot_34](https://user-images.githubusercontent.com/104158199/168023443-431c70fb-29c1-439c-a2ce-4435db05e7aa.png)

**Comment by scholokov** [comment]
fixed

**Comment by MykhailoBorovikov** [comment]
Verified
