### ISSUE TITLE
Program - QA Program - Github: Wrong link to the lesson 'GitHub – Code'

### ISSUE THREAD

**Issue by MykhailoBorovikov** [scholokov/qax-portal#217]
Wrong link to the lesson in course <a href="https://portal.qax-camp.com.ua/courses/github/">Github</a>

**Preconditions:** 
Be logged in

**STR:**
1) Open Program - QA Program
2) Scroll donw to Github
3) Open Github course
4) Click on 'GitHub – Code'

**Actual:**
Link is wrong and lesson do not opens

**Expected:** 
Link is correct and lesson opens
![Screenshot_35](https://user-images.githubusercontent.com/104158199/168023719-a366ddf2-b812-45eb-8c73-e3c1807558ce.png)

**Comment by scholokov** [comment]
fixed

**Comment by MykhailoBorovikov** [comment]
Verified
