### ISSUE TITLE
Program - QA Program - Github: Wrong link to the lesson 'GitHub – How To Create A Bug'

### ISSUE THREAD

**Issue by MykhailoBorovikov** [scholokov/qax-portal#218]
Wrong link to the lesson in course <a href="https://portal.qax-camp.com.ua/courses/github/">Github</a>

**Preconditions:** 
Be logged in

**STR:**
1) Open Program - QA Program
2) Scroll donw to Github
3) Open Github course
4) Click on 'GitHub – How To Create A Bug'

**Actual:**
Link is wrong and lesson do not opens

**Expected:** 
Link is correct and lesson opens
![Screenshot_36](https://user-images.githubusercontent.com/104158199/168024119-6b7b4e20-4d0c-4b35-9cef-06351bb0b064.png)

**Comment by scholokov** [comment]
fixed

**Comment by MykhailoBorovikov** [comment]
Verified
