### ISSUE TITLE
Program - QA Program - Github: Wrong link to the lesson 'GitHub – Work With Issues'

### ISSUE THREAD

**Issue by MykhailoBorovikov** [scholokov/qax-portal#219]
Wrong link to the lesson in course <a href="https://portal.qax-camp.com.ua/courses/github/">Github</a>

**Preconditions:** 
Be logged in

**STR:**
1) Open Program - QA Program
2) Scroll donw to Github
3) Open Github course
4) Click on 'GitHub – Work With Issues'

**Actual:**
Link is wrong and lesson do not opens

**Expected:** 
Link is correct and lesson opens

![Screenshot_37](https://user-images.githubusercontent.com/104158199/168024375-05a91c1b-fda5-48ce-8bef-103ceff5e149.png)

**Comment by scholokov** [comment]
fixed

**Comment by MykhailoBorovikov** [comment]
Verified
