### ISSUE TITLE
Program - QA Program - Github: Wrong link to the lesson 'GitHub – How To Upload Images'

### ISSUE THREAD

**Issue by MykhailoBorovikov** [scholokov/qax-portal#220]
Wrong link to the lesson in course <a href="https://portal.qax-camp.com.ua/courses/github/">Github</a>

**Preconditions:** 
Be logged in

**STR:**
1) Open Program - QA Program
2) Scroll donw to Github
3) Open Github course
4) Click on 'GitHub – How To Upload Images'

**Actual:**
Link is wrong and lesson do not opens

**Expected:** 
Link is correct and lesson opens
![Screenshot_38](https://user-images.githubusercontent.com/104158199/168025162-a6f3564d-7d3f-4dca-a520-b674b91ee291.png)

**Comment by scholokov** [comment]
fixed

**Comment by MykhailoBorovikov** [comment]
Verified
