### ISSUE TITLE
Program - QA Program - Github: Wrong link to the lesson 'GitHub – How To Create Tables'

### ISSUE THREAD

**Issue by MykhailoBorovikov** [scholokov/qax-portal#221]
Wrong link to the lesson in course <a href="https://portal.qax-camp.com.ua/courses/github/">Github</a>

**Preconditions:** 
Be logged in

**STR:**
1) Open Program - QA Program
2) Scroll donw to Github
3) Open Github course
4) Click on 'GitHub – How To Create Tables'

**Actual:**
Link is wrong and lesson do not opens

**Expected:** 
Link is correct and lesson opens
![Screenshot_39](https://user-images.githubusercontent.com/104158199/168025439-6fbd0446-5031-4731-8add-fe4b158f5125.png)

**Comment by scholokov** [comment]
fixed

**Comment by MykhailoBorovikov** [comment]
Verified
