### ISSUE TITLE
Program - QA Program - Github: Wrong sequence of lesson topics

### ISSUE THREAD

**Issue by MykhailoBorovikov** [scholokov/qax-portal#222]
Wrong sequence of lesson topics in <a href="https://portal.qax-camp.com.ua/courses/github/">Github course</a>

**Preconditions:**
Be logged in
Open <a href="https://portal.qax-camp.com.ua/courses/github/">Github course</a>

**STR:**

1) Click on 'Expand All' button 
2) Focus on sequnce of topics

**Actual:**

1. GitHub – Overal Overview
2. GitHub – Work with Issues
3. GitHub – How To Upload Images
4. GitHub – Actions
5. GitHub – Code
6. GitHub – Development Flow
7. GitHub – How To Create a Bug?
8. GitHub – How To Create Tables
9. GitHub – How To Create Labels and Boards

**Expected:**

1. GitHub – Overal Overview
2. GitHub – Development Flow
3. GitHub – Actions
4. GitHub – Code
5. GitHub – How To Create a Bug?
6. GitHub – Work with Issues
7. GitHub – How To Upload Images
8. GitHub – How To Create Tables
9. GitHub – How To Create Labels and Board
![Screenshot_40](https://user-images.githubusercontent.com/104158199/168050021-b3dfaa8f-9156-4e09-b518-1901a8b3738a.png)

**Comment by scholokov** [comment]
fixed

**Comment by MykhailoBorovikov** [comment]
Verified
