### ISSUE TITLE
Program - QA Program - HR - Составление резюме - Составление резюме (CV) – From HR Side: Wrong author of lesson

### ISSUE THREAD

**Issue by MykhailoBorovikov** [scholokov/qax-portal#223]
Wrong author of lesson <a href="https://portal.qax-camp.com.ua/courses/cv/lessons/cv-hr/">Составление резюме (CV) – From HR Side</a>

**Preconditions:** 
Be logged in
Open <a href="https://portal.qax-camp.com.ua/courses/cv/lessons/cv-hr/">Составление резюме (CV) – From HR Side</a>

**STR:** 

1. Scroll down
2. Focus on author

**Actual:**
Denis Scholokov

**Expected:**
Olga Companets or Daria Kazarinova
![Screenshot_41](https://user-images.githubusercontent.com/104158199/168054528-2ddbd5e4-9b2c-426f-b21e-383c39951bb0.png)

**Comment by scholokov** [comment]
@MykhailoBorovikov 
шаги не забывай нумеровать

**Comment by MykhailoBorovikov** [comment]
> @MykhailoBorovikov шаги не забывай нумеровать

исправил

**Comment by GeorgiiZ90** [comment]
Fixed

**Comment by MykhailoBorovikov** [comment]
Verified
