### ISSUE TITLE
Program - QA Program - Course - Роли и артефакты в проектной команде - table of contents "Системный Архитектор" wrong url

### ISSUE THREAD

**Issue by MykhailoBorovikov** [scholokov/qax-portal#225]
Precondition: Be logged in

Steps to reproduce:

1) Open portal.qax-camp.com.ua
2) Open a tab Program on the navigation menu - QA Program - Роли и артефакты в проектной команде 
3) Open course content "Роли и артефакты в проектной команде" - <a href="https://portal.qax-camp.com.ua/courses/project-team/lessons/roles-in-team/">Роли и артефакты в проектной команде </a>
4) Pay attention on "Системный Архитектор" link at contents table

Actual result:

Link contains wrong URL: https://portal.qax-camp.com.ua/project-team/#systemarchitect

Expected result:

Link contains wright URL: https://portal.qax-camp.com.ua/courses/project-team/lessons/roles-in-team/#systemarchitect
![Screenshot_42](https://user-images.githubusercontent.com/104158199/168232863-9f303aba-6927-4e7c-8611-50d4b012da4b.png)

**Comment by scholokov** [comment]
Actual result:

Link contains wrong URL: https://portal.qax-camp.com.ua/project-team/#systemarchitect

Expected result:

Link contains wright URL: https://portal.qax-camp.com.ua/courses/project-team/lessons/roles-in-team/#systemarchitect

если ты говоришь о том что некие сущности разные (разные линки например, либо название разное, всегда удобнее это писать с новой строки, так глазу проще сравнивать):


Actual result:
Link contains wrong URL: 
https://portal.qax-camp.com.ua/project-team/#systemarchitect

Expected result:
Link contains wright URL: 
https://portal.qax-camp.com.ua/courses/project-team/lessons/roles-in-team/#systemarchitect

особенно это заметно, когда разное количесво символов в "первой части предложения" (у тебя "Link contains wright URL: " тут вышло одинаковое количесво символов, из-за опечатки)

**Comment by scholokov** [comment]
fixed

**Comment by MykhailoBorovikov** [comment]
Verified
