### ISSUE TITLE
Trainers page: table rows have different color in 'night mode'

### ISSUE THREAD

**Issue by MykhailoBorovikov** [scholokov/qax-portal#226]
#134 
When switch to 'night mode' table rows are colored differently.

Preconditions: 
Open <a href="https://portal.qax-camp.com.ua/trainers/">Our team</a>
Sure that page is in 'day mode' 

STR:
1)Switch page to 'night mode'
2) Focus on trainers's info tables

Actual:
Tables have rows in two different colors: #202e42 and #f0f0f0

Expected: 
Tables have rows in one color: #202e42

![Screenshot_44](https://user-images.githubusercontent.com/104158199/168242922-ebfa03a5-141b-4cbe-8b0b-770dbfc28cdb.png)

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by MykhailoBorovikov** [comment]
Issue is still present

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by MykhailoBorovikov** [comment]
Verified
