### ISSUE TITLE
Program - QA Program - Базовые программы для QA - Jira: lesson content missing

### ISSUE THREAD

**Issue by MykhailoBorovikov** [scholokov/qax-portal#230]
Lesson content missing

**Preconditions:**
Opened https://portal.qax-camp.com.ua/
Be logged in

**STR:**

1. Open Program - QA Program
2. Scroll down to Базовые программы для QA
3. Open Jira course
4. Open lesson Jira - Создание задачи/бага

**Actual:**
Lesson content is missing

**Expected:**

Lesson content is present
![Screenshot_50](https://user-images.githubusercontent.com/104158199/168590568-886837e2-71db-454c-b1ac-d462094be736.png)

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by MykhailoBorovikov** [comment]
Verified
