### ISSUE TITLE
QA Program - Базы данных, SQL: Lesson 'SQL - Основы выборки данных' URL contains wrong characters

### ISSUE THREAD

**Issue by MykhailoBorovikov** [scholokov/qax-portal#236]
#233 
Lesson URL contains wrong characters (https://portal.qax-camp.com.ua/courses/sql/lessons/sql-%d0%be%d1%81%d0%bd%d0%be%d0%b2%d1%8b-%d0%b2%d1%8b%d0%b1%d0%be%d1%80%d0%ba%d0%b8-%d0%b4%d0%b0%d0%bd%d0%bd%d1%8b%d1%85/)

**Preconditions:**
Opened https://portal.qax-camp.com.ua/
Be logged in

**STR:**

1. Open QA Program - Базы данных, SQL
2. Click on SQL - Основы выборки данных
3. Focus lesson URL

**Actual:**
URS contains russian characters

**Expected:**
URL contains only english characters
![Screenshot_56](https://user-images.githubusercontent.com/104158199/169666142-e8bf5812-b683-4f96-a5fd-1e6f65cfb42d.png)

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by MykhailoBorovikov** [comment]
Verified
