### ISSUE TITLE
QA Program - Базы данных, SQL: Lesson 'SQL – Основы выборки данных – Часть 2' URL contains wrong characters

### ISSUE THREAD

**Issue by MykhailoBorovikov** [scholokov/qax-portal#237]
#233 
Lesson URL contains wrong characters (https://portal.qax-camp.com.ua/courses/sql/lessons/sql-%d0%be%d1%81%d0%bd%d0%be%d0%b2%d1%8b-%d0%b2%d1%8b%d0%b1%d0%be%d1%80%d0%ba%d0%b8-%d0%b4%d0%b0%d0%bd%d0%bd%d1%8b%d1%85-%d1%87%d0%b0%d1%81%d1%82%d1%8c-2/)

**Preconditions:**
Opened https://portal.qax-camp.com.ua/
Be logged in

**STR:**

1. Open QA Program - Базы данных, SQL
2. Click on SQL – Основы выборки данных – Часть 2
3. Focus lesson URL

**Actual:**
URS contains russian characters

**Expected:**
URL contains only english characters
![Screenshot_57](https://user-images.githubusercontent.com/104158199/169666192-3e87b02d-ada9-4697-b209-312db6d6ae84.png)

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by MykhailoBorovikov** [comment]
Verified
