### ISSUE TITLE
QA Program - Базы данных, SQL: Lesson 'Еще немного SQL' URL contains wrong characters

### ISSUE THREAD

**Issue by MykhailoBorovikov** [scholokov/qax-portal#238]
#233 
Lesson URL contains wrong characters (https://portal.qax-camp.com.ua/courses/sql/lessons/%d0%b5%d1%89%d0%b5-%d0%bd%d0%b5%d0%bc%d0%bd%d0%be%d0%b3%d0%be-sql/)

**Preconditions:**
Opened https://portal.qax-camp.com.ua/
Be logged in

**STR:**

1. Open QA Program - Базы данных, SQL
2. Click on Еще немного SQL
3. Focus lesson URL

**Actual:**
URS contains russian characters

**Expected:**
URL contains only english characters
![Screenshot_58](https://user-images.githubusercontent.com/104158199/169666242-95f5040b-1be2-45b1-afe7-d60048473ca5.png)

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by MykhailoBorovikov** [comment]
Verified
