### ISSUE TITLE
QA Program - Базы данных, SQL: Lesson 'Еще немного SQL' wrong preview image

### ISSUE THREAD

**Issue by MykhailoBorovikov** [scholokov/qax-portal#239]
#233 
Wrong preview image at lesson Еще немного SQL (https://portal.qax-camp.com.ua/courses/sql/lessons/little-more-sql/)

**Preconditions:**
Opened https://portal.qax-camp.com.ua/
Be logged in

**STR:**

1. Open QA Program - Базы данных, SQL
2. Click on Еще немного SQL
3. Focus on preview image

**Actual:**
Preview image is default

**Expected:**
Preview image must be unique or the same as course preview image
![Screenshot_59](https://user-images.githubusercontent.com/104158199/169666333-c3ba166e-c5c4-41df-b44e-bc03cf71a89d.png)

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by MykhailoBorovikov** [comment]
Issue is still present

**Comment by scholokov** [comment]
дай прямую ссылку на статью. а то там их 2. и на одну есть, а на вторую - нет

**Comment by MykhailoBorovikov** [comment]
> дай прямую ссылку на статью. а то там их 2. и на одну есть, а на вторую - нет

добавил

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by MykhailoBorovikov** [comment]
Verified
