### ISSUE TITLE
QA Program - Базовые программы для QA: No access to the course

### ISSUE THREAD

**Issue by MykhailoBorovikov** [scholokov/qax-portal#240]
#234 
No access to the course content (https://portal.qax-camp.com.ua/courses/qa-basic-programs/)

Preconditions:
Opened https://portal.qax-camp.com.ua/
Be logged in

STR:

Open QA Program -  Базовые программы для QA
Place the cursor on Test Management System (TMS) lesson

Actual:
Message: You don't have access to this content. Content is unavaliable

Expected:
No message and content is content available
![Screenshot_60](https://user-images.githubusercontent.com/104158199/169666686-c7bef354-f5e7-4475-a3f1-9a71c8f57038.png)

**Comment by scholokov** [comment]
для удобства добавь еще плиз прямую линку на курс

**Comment by MykhailoBorovikov** [comment]
> для удобства добавь еще плиз прямую линку на курс

done

**Comment by scholokov** [comment]
fixed

**Comment by MykhailoBorovikov** [comment]
Verified
