### ISSUE TITLE
QA Program - Теория тестирования: missing lessons

### ISSUE THREAD

**Issue by MykhailoBorovikov** [scholokov/qax-portal#247]
Missing lessons in course (https://portal.qax-camp.com.ua/courses/testing-theory/)

**Preconditions:**
Opened https://portal.qax-camp.com.ua/
Be logged in

**STR:**

1. Open QA Program - Теория тестирования
2. Focus on list of lessons

**Actual:**
Verification VS Validation
Traceability matrix
Test Plan vs Test Strategy
Тест Дизайн – Техники

**Expected:**
Verification VS Validation
Traceability matrix
Test Plan vs Test Strategy
Load Testing
Priority VS Severity
Metrics

![Screenshot_73](https://user-images.githubusercontent.com/104158199/170839050-bce429da-a1e2-4341-8501-1f94584b5dce.png)
![Screenshot_74](https://user-images.githubusercontent.com/104158199/170839052-45077c57-fef2-4554-b31a-b7e28d4cfe49.png)

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by MykhailoBorovikov** [comment]
verified

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by MykhailoBorovikov** [comment]
VErified
