### ISSUE TITLE
QA Program - QA Basics: wrong sequence of lessons

### ISSUE THREAD

**Issue by MykhailoBorovikov** [scholokov/qax-portal#248]
#232 
Wrong sequence of lessons in course (https://portal.qax-camp.com.ua/courses/qa-basics/)

**Preconditions:**
Opened https://portal.qax-camp.com.ua/
Be logged in

**STR:**

1. Open QA Program - QA Basics
2. Focus on list of lessons

**Actual:**
Тестировщик. Кто это?
Виды тестирования
Уровни тестирования, Пирамида тестов
Defect
Test Documentation: тест кейс и чек-лист
_**Task / Issue flow**
**Requirements: зачем их тестировать**
**Тестирование требований**
**Роли и артефакты в проектной команде**_
SDLC / STLC

**Expected:**
Тестировщик. Кто это?
Виды тестирования
Уровни тестирования, Пирамида тестов
Defect
Test Documentation: тест кейс и чек-лист
_**Requirements: зачем их тестировать**
**Тестирование требований**
**Роли и артефакты в проектной команде**
**Task / Issue flow**_
SDLC / STLC

More details see in <a href="https://github.com/scholokov/qax-portal/wiki/2.-Portal-structure">wiki</a>

![Screenshot_76](https://user-images.githubusercontent.com/104158199/170839425-4c7790a3-71b3-4280-bf6f-009215d357ba.png)

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by MykhailoBorovikov** [comment]
verified

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by MykhailoBorovikov** [comment]
verified
