### ISSUE TITLE
Website optimization

### ISSUE THREAD

**Issue by Eugen-Ts** [scholokov/qax-portal#249]
Need to optimization speed  site downloads

**Comment by scholokov** [comment]
выполнено
для получения доступа к сайту необходимо в файле host (на windows: Windows\System32\drivers\etc\hosts) добавить строку:
185.104.45.153 portal.qax-camp.com.ua

**Comment by MykhailoBorovikov** [comment]
Тесты говорят, что изменений в скорости работы сайта нет. 
Сравниваю с  #136 
![Screenshot_82](https://user-images.githubusercontent.com/104158199/171923009-cb0992ac-da48-4897-a4fd-a6a60a3a5dd8.png)
![Screenshot_83](https://user-images.githubusercontent.com/104158199/171923068-b4aefe0c-0783-4b58-bfe6-6382189d605e.png)
![Screenshot_84](https://user-images.githubusercontent.com/104158199/171923302-70bba0d9-5204-45da-aff2-8db0db60d16c.png)
![Screenshot_85](https://user-images.githubusercontent.com/104158199/171923306-bbde60e7-3b78-4972-a9df-843b6a2e27ce.png)

**Comment by MykhailoBorovikov** [comment]
@Eugen-Ts уже сделано (:

**Comment by MykhailoBorovikov** [comment]
Есть обновленные данные:
Сократилось время прорисовок. Уменьшился размер загружаемого контента. 
В целом быстродействие выросло, но не по всем параметрам вышло в "зеленую" зону. 
![Screenshot_95](https://user-images.githubusercontent.com/104158199/173192398-4eafb2d0-1471-4dfa-9e56-17f3f129ed7f.png)
![Screenshot_96](https://user-images.githubusercontent.com/104158199/173192399-54f38b07-fd34-4974-9be5-cb85515874e2.png)
![Screenshot_97](https://user-images.githubusercontent.com/104158199/173192400-9049f3d5-2ee6-4508-90e4-ab5ccc8000f2.png)
![Screenshot_98](https://user-images.githubusercontent.com/104158199/173192401-a318d2fa-3d6b-45e0-989d-0be5d028332c.png)

**Comment by scholokov** [comment]
ок. на данный момент этого достаточно. можем закрывать. 
когда имплементируем новый дизайн вернемся к замерам
