### ISSUE TITLE
QA Program - курс QA Basics - Картинка превью курса = Картинка превью курса по умолчанию

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal#250]
Шаги воспроизведения:
1) Перейти в среду: https://portal.qax-camp.com.ua/qa-basics/
2) Обратить внимание на превью курса

Ожидаемый результат:
Превью картинка курса отличается от "по умолчанию"

Фактический результат:
Превью картинка курса не отличается от "по умолчанию"

Операционная система:
Windows 10

Браузер:
Chrome  102.0.5005.63 (64 бит)

![QA Basics – QAX Camp - Google Chrome 01 06 2022 17_59_56](https://user-images.githubusercontent.com/95171672/171439986-ba74f889-cb13-4484-af57-54c188ba6e5a.png)

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
verified
