### ISSUE TITLE
QA Program - курс QA Basics - Картинка превью курса не уникальна

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal#251]
Шаги воспроизведения:
1) Перейти в среду: https://portal.qax-camp.com.ua/qa-basics/
2) Обратить внимание на превью курса

Ожидаемый результат:
Превью картинка курса уникальна

Фактический результат:
Превью картинка курса не уникальна

Операционная система:
Windows 10

Браузер:
Chrome 102.0.5005.63 (64 бит)

![QA Basics – QAX Camp - Google Chrome 01 06 2022 17_59_56](https://user-images.githubusercontent.com/95171672/171441902-efde4d8c-ed29-4970-8a68-58aeae6b176b.png)
![QA Basics – QAX Camp - Google Chrome 01 06 2022 18_26_16_LI](https://user-images.githubusercontent.com/95171672/171442211-da1d7758-b35e-4d4a-8a0b-9ffc685e13ca.jpg)

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
verified
