### ISSUE TITLE
Home - Projects - Неверное название раздела "Проэкты"

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal#257]
Шаги воспроизведения:
1) Перейти в среду: http://portal.qax-camp.com.ua/qa-program/
2) Навести курсор на кнопку Projects
3) Посмотреть на название раздела "Проэкты"

Ожидаемый результат:
Название раздела = Проекты

Фактический результат:
Название раздела = Проэкты

Операционная система:
Windows 10

Браузер:
Chrome
![QAX Camp – Students Portal - Google Chrome 09 06 2022 17_33_58_LI](https://user-images.githubusercontent.com/95171672/172875814-c3bbe9d0-7059-4c51-8b6d-622a3f02f481.jpg)

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
verified
