### ISSUE TITLE
Statistics - Wrong HTTP

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal#286]
Steps of reproducing:
1) Open http://portal.qax-camp.com.ua/statistics/
2) View HTTP protocol

Expacted Result:
http

Actual Result:
https

Environments:
Windows 10, Chrome 103.0.5060.134 (64 bit)
Android 8.1.0, Chrome 103.0.5060.71
![Statistics – QAX Camp - Google Chrome 24 07 2022 17_25_15](https://user-images.githubusercontent.com/95171672/180651935-03ec3951-a0f6-4d94-ba5b-8ffa88a1fdfa.png)
![photo_2022-07-24_17-31-03](https://user-images.githubusercontent.com/95171672/180651860-fb8d4984-19dd-4519-ac0e-283772645702.jpg)

**Comment by scholokov** [comment]
а в чем проблема?
все себя корректно ведет...
