### ISSUE TITLE
Головна - Structural block "Календарик с расписанием" is missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/qax-portal#290]
Steps of reproducing:
1) Open https://portal.qax-camp.com.ua/programs/

Expected Result:
Structural block "Календарик с расписанием" is present

Actual Result:
Structural block "Календарик с расписанием" is missing

Environments:
Windows 10, Chrome 103.0.5060.134 (64 bit)
Android 8.1.0, Chrome 103.0.5060.129
![QAX Camp – Students Portal - Google Chrome 26 07 2022 16_16_56](https://user-images.githubusercontent.com/95171672/181016644-06050d46-d20f-460f-ab3c-e7b54e2c8b67.png)
![photo_2022-07-26_16-25-35](https://user-images.githubusercontent.com/95171672/181017154-10fd0859-bb83-4e2c-bb9e-247ffd59ffc3.jpg)

**Comment by scholokov** [comment]
в соответствии с последним дизайном там нет календарика

**Comment by DmitriiNasonov** [comment]
bug is not actual
