### ISSUE TITLE
Сheck adjenda for usability on a white theme

### ISSUE THREAD

**Issue by etaranyuk** [scholokov/qax-portal#40]

**Comment by Olesya0518** [comment]
@etaranyuk More information is needed on this task.

**Comment by Eugen-Ts** [comment]
@Olesya0518 Алеся, прописываю подробней, что нужно проверить. 
Когда на портале мы переключаем слайдер на светлый фон могут быть не читабельными тексты.
Необходимо протестировать страницу: https://portal.qax-camp.com.ua/qa-start-cource/ и аналогичные ей.

Но на сколько сейчас вижу текст стал читабельным за счет более темного шрифта. Думаю можно переносить в Resolved.
Что скажете @Olesya0518 @etaranyuk @scholokov

**Comment by Olesya0518** [comment]
@Eugen-Ts Евгений, там требования другие к аджанде, я завела баг, посмотри в ожидаемом результате и описание прочитай. Пропиши пожалуйста в описании этой таски требования к ней, чтобы для других было понятно, добавь описания и линку
