### ISSUE TITLE
Translate test plan in English.

### ISSUE THREAD

**Issue by Eugen-Ts** [scholokov/qax-portal#49]
Translate test plan in English.
Test plan link: https://docs.google.com/document/d/13oPwQjffZwLPqn8e4w7mBH2Pc8MCc1EV/edit

**Comment by Tipaieva** [comment]
Test Plan translated from Russian into English. Please check it https://docs.google.com/document/d/1VYmFO4HVkiKEh_HunmQkMrbOq9BJlwB95R1XtoHNjog/edit?usp=sharing
