### ISSUE TITLE
Course "Requirements": wrong author of the article "Requirements: зачем их тестировать"

### ISSUE THREAD

**Issue by Tipaieva** [scholokov/qax-portal#55]
### Discription:
At the end of the article "Requirements: зачем их тестировать" marked wrong author of the article. Сhange the author of the article from Denis Scholokov to Rudchenko Yuliya

### Steps:
1. Open site 
2. Select "QA Программа" - "Теория тестирования" - "Requirements" - "Course Content" 
3. Click "Requirements: зачем их тестировать" and go to at the end of the article

### Actual:
**Denis Scholokov** is listed as the author of the article

### Expected:
**Rudchenko Yuliya** is listed as the author of the article

### Environment:
Decktop/ Windows 10 Pro/ Google Chrome 95.0.4638.54 (64 bit)

### Attachments:
![image](https://user-images.githubusercontent.com/92110820/140911271-fd3e765b-1a51-4d57-b051-4085a25ee366.png)

**Comment by scholokov** [comment]
change author of the article
в багах не должно быть "указательных действий", т.е. надо формулировать фразы без указания что надо сделать.

например 
wrong author of the article

**Comment by scholokov** [comment]
в одном шаге перечисленно слишком много действий, нечиталебльно
In the header select "QA Программа" and go to the section "Теория тестирования", click "Requirements" and in "Course Content" select "Requirements: зачем их тестировать" and go to the end of the article

**Comment by scholokov** [comment]
fixed

**Comment by Tipaieva** [comment]
verified
