### ISSUE TITLE
Course GitHub: page of lesson ""GitHub – How To Create Labels and Boards" no content and displayed the error message

### ISSUE THREAD

**Issue by Tipaieva** [scholokov/qax-portal#56]
### Discription:
The page of lesson "GitHub – How To Create Labels and Boards" has no content and displayed the error message, after press the button"Mark Complete" of all the previous lessons on the GitHub course, 

### Steps:
1. Open site
2. Select "QA Программа - Базовые программы для QA - GitHub".
3. Press the button "Mark Complete" in "Course Content":

- "GitHub – Overal Overview",
- "GitHub – Development Flow", 
- "GitHub – Actions",  
- "GitHub – Code", 
- "GitHub – How To Create a Bug?", 
- "GitHub – Work with Issues", 
- "GitHub – How To Upload Images", 
- "GitHub – How To Create Tables".

4. Click "GitHub – How To Create Labels and Boards"

### Actual:
- **no content and displayed the error message** "Please go back and complete the previous lesson"

### Expected:
- lesson **page opened** with content of the educational material 

### Environment:
Decktop/ Windows 10 Pro/ Google Chrome 95.0.4638.54 (64 bit)
Mobili/ Xiaomi Mi 11 Lite MIUI Global 12.5.6 Stable/ Google Chrome 95.0.4638.74 / Android 11 RKQ1.200826.002

### Attachments:
![image](https://user-images.githubusercontent.com/92110820/140922324-d2de683d-ee3e-4efb-a68b-1b22e8a79a15.png)

**Comment by scholokov** [comment]
please retest

**Comment by Tipaieva** [comment]
does not open (tested in Desctop and Mobile)

**Comment by MykhailoBorovikov** [comment]
Verification is blocked by issue #214

**Comment by scholokov** [comment]
fixed

**Comment by MykhailoBorovikov** [comment]
Verified
