### ISSUE TITLE
QA Программа - missing the pdf-fail " Тестирование Программного Обеспечения - Святослав Куликов - 3rd edition - 2021.pdf"

### ISSUE THREAD

**Issue by Tipaieva** [scholokov/qax-portal#57]
### Discription:
Pdf-fail "Тестирование Программного Обеспечения - Святослав Куликов - 3rd edition - 2021.pdf" is on the page QA https://portal.qax-camp.com.ua/qa-start-sw/ , but the pdf-fail "Тестирование Программного Обеспечения - Святослав Куликов - 3rd edition - 2021.pdf" missing on the page QA Программа

### Steps:
1. Open site
2. Select QA Программа

### Actual:
**missing** the pdf-fail " Тестирование Программного Обеспечения - Святослав Куликов - 3rd edition - 2021.pdf" 

### Expected:
**present and displayed** the pdf-fail " Тестирование Программного Обеспечения - Святослав Куликов - 3rd edition - 2021.pdf" 

### Attachments:
![image](https://user-images.githubusercontent.com/92110820/141107357-784f1f77-9847-4ba6-a01b-581dbe1b2202.png)

**Comment by scholokov** [comment]
Move the pdf-fail 
та же проблема что и вчера.
тебе надо ссылать что в старом варианте есть, а в новом - нет, типо как у тебя в теме написано, но такое должно быть и в дескрипшене тоже

**Comment by scholokov** [comment]
лучше ссылочку в тело давать не курса, а конкретно еурса или урока, в котором проблема

**Comment by scholokov** [comment]
книга исключена из этого урока
создан отдельный урок и курс
"Книга: Святослав Куликов – Тестирование Программного Обеспечения"
добавлена в блок:
"Entry level"
с отметкой "дополнительный материал"
"Extra"

**Comment by Tipaieva** [comment]
verified
