### ISSUE TITLE
QA Программа: Cource Введение в тестирование ПО - video contains 3 topics instead of 1

### ISSUE THREAD

**Issue by Tipaieva** [scholokov/qax-portal#58]
### Discription:
In the lesson Введение в тестирование ПО the video contains 3 different topics for 3 lessons: Ведение в тестирование ПО, Участники проектной команды, Defect Management. Replace the video so that it contains only 1 lesson on the 1 topic Введение в тестирование ПО as on the page  https://portal.qax-camp.com.ua/qa-start-sw/ 

### Steps:
1. Open site
2. Select QA Программа - Введение в тестирование ПО
3. Open the lesson - Введение в тестирование ПО
4. Reproduce the video

### Actual:
- video **contains 3 different** topics for 3 lessons

###  Expected:
- video **contains only 1** topic for 1 lesson

### Environment:
Decktop / Windows 10 Pro/ Google Chrome 95.0.4638.69 (64 bit)

### Attachments:
![image](https://user-images.githubusercontent.com/92110820/141111935-dabc9208-8d85-4574-889d-3a6e87626cc1.png)

**Comment by scholokov** [comment]
In the lesson Введение в тестирование ПО the video contains 3 different topics for 3 lessons: Ведение в тестирование ПО, Участники проектной команды, Defect Management, instead of 1 lesson on the 1 topic Введение в тестирование ПО as on the page https://portal.qax-camp.com.ua/qa-start-sw/

**Comment by scholokov** [comment]
тайтл должен быть более специфичным
QA Программа: Cource Введение в тестирование ПО - video contains unnecessary information
например
QA Программа: Cource Введение в тестирование ПО - video contains 3 topics instead of 1

**Comment by scholokov** [comment]
fixed

**Comment by Tipaieva** [comment]
verified

**Comment by Tipaieva** [comment]
The lesson Введение в тестирование ПО moved in obsolete according to the message received from Denis Scholokov to Tipaieva Valentina

![image](https://user-images.githubusercontent.com/92110820/142831475-5bfcc58a-8600-43b7-aee0-a9178aa31e31.png)

**Comment by Tipaieva** [comment]
@scholokov материалы issue #84 перенесены в устаревшие https://portal.qax-camp.com.ua/courses/old/, предлагаю материалы данного бага (issue #58) переместить также в устаревшие https://portal.qax-camp.com.ua/courses/old/.

**Comment by scholokov** [comment]
исправлено в соответствии с предложением

**Comment by Tipaieva** [comment]
verified
issue #131 is introduced
