### ISSUE TITLE
Transfer articles to lessons

### ISSUE THREAD

**Issue by alexandersamukha** [scholokov/qax-portal#59]
* articles have to transfer to lessons
* create new courses which include lessons & tests
* Update table with courses for QA: https://docs.google.com/spreadsheets/d/1LkrguJrv4dOF9T8rwai_6JRBGm83qjxb7baEXKASgBs/edit#gid=0
* fulfill test status in column «Тесты готовые»

**Comment by Tipaieva** [comment]
articles have been moved to lessons
сourse created, 
table updated, 
no tests

**Comment by scholokov** [comment]
добавлен урок:
"Тестирование требований"
в курс "Requirements"
в блок "Теория тестирования"

**Comment by scholokov** [comment]
добавлен урок:
"Тестировщик. Кто это?"
в курс "Введение в тестирование ПО"
в блок "Entry level"

**Comment by scholokov** [comment]
урок отправлен в устаревшее:
"Введение в тестирование ПО"
в курс "Введение в тестирование ПО"
в блок "Entry level"

**Comment by scholokov** [comment]
добавлен новый курс
"Особенности тестирования десктопных приложений"

**Comment by scholokov** [comment]
добавлен урок
"Особенности тестирования десктопных приложений"
в курс
"Особенности тестирования десктопных приложений"
в раздел:
"Особенности тестирования на различных платформах"

**Comment by scholokov** [comment]
создан курс "Устаревшее"
куда будут переносится устарешшие уроки
в меню пока не добавлял, так не придумал пока куда
доступно по прямому линку:
https://portal.qax-camp.com.ua/courses/old/

**Comment by scholokov** [comment]
создан отдельный урок и курс
"Книга: Святослав Куликов – Тестирование Программного Обеспечения"
добавлена в блок:
"Entry level"
с отметкой "дополнительный материал"
"Extra"

**Comment by scholokov** [comment]
добавлен урок Postman
в курс Postman
блок Web technologies
обязателен к прохождению

**Comment by scholokov** [comment]
добавлен урок
Обучение – это привычка! – Андрей Курпатов
в курс
Обучение – это привычка! – Андрей Курпатов
блок
Soft Skills development

**Comment by scholokov** [comment]
добавлен урок
Art Of Leadership
курс
Art Of Leadership
блок
Soft Skills development

**Comment by scholokov** [comment]
создан урок и добавлен контент
Составление резюме (CV) from the Tech Side
добавлен курс
Составление резюме (CV)
блок
HR

**Comment by scholokov** [comment]
добавлен урок
Веселое выступление о необычных дизайнах продуктов
в курс
UI
в блок
Web, Mobile, UI – Testing
необязателен, для прохождения

**Comment by scholokov** [comment]
создан новый урок
Devtools – Как посмотреть характеристики шрифта на сайте
добавлен в курс
Devtools 
в блок
Web, Mobile, UI – Testing

**Comment by scholokov** [comment]
создан новый урок
Составление резюме (CV) – From HR Side
добавлен в курс
Составление резюме (CV)
в блок
HR

**Comment by scholokov** [comment]
создан новый урок
LinkedIn
создан новый курс
LinkedIn
в блок
HR

**Comment by scholokov** [comment]
созданы новые уроки
Как пройти собеседование – From HR Side
Как пройти собеседование – From Tech Side
создан новый курс
Как пройти собеседование
в блок
HR

**Comment by scholokov** [comment]
создан новый урок
Task / Issue flow
создан новый курс
Task / Issue flow
в блок
Теория тестирования

**Comment by scholokov** [comment]
создан новый урок
Jira – Dashboards
добавлен в курс
Jira
в блок
Базовые программы для QA

**Comment by scholokov** [comment]
создан новый урок
Jira – Filters, Bulk Tasks Edit
добавлен в курс
Jira
в блок
Базовые программы для QA

**Comment by scholokov** [comment]
создан новый урок
Test Plan vs Test Strategy
добавлен в курс
Test Plan vs Test Strategy
в блок
Теория тестирования

**Comment by Eugen-Ts** [comment]
> Теория тестирования

done

**Comment by Eugen-Ts** [comment]
> Entry level

done

**Comment by Eugen-Ts** [comment]
> Entry level

done

**Comment by Eugen-Ts** [comment]
> Особенности тестирования десктопных приложений

done

**Comment by Eugen-Ts** [comment]
> Особенности тестирования на различных платформах

done

**Comment by Eugen-Ts** [comment]
> создан курс "Устаревшее" куда будут переносится устарешшие уроки в меню пока не добавлял, так не придумал пока куда доступно по прямому линку: https://portal.qax-camp.com.ua/courses/old/

done

**Comment by Eugen-Ts** [comment]
> Entry level

done

**Comment by Eugen-Ts** [comment]
> Web technologies

done

**Comment by Eugen-Ts** [comment]
> Soft Skills development

done

**Comment by Eugen-Ts** [comment]
> 

done

**Comment by Eugen-Ts** [comment]
> HR

done

**Comment by Eugen-Ts** [comment]
> необязателен, для прохождения

done

**Comment by Eugen-Ts** [comment]
> Devtools – Как посмотреть характеристики шрифта на сайте

done

**Comment by Eugen-Ts** [comment]
> Составление резюме (CV) – From HR Side

done

**Comment by Eugen-Ts** [comment]
> LinkedIn

done

**Comment by Eugen-Ts** [comment]
> Как пройти собеседование – From HR Side

done

**Comment by Eugen-Ts** [comment]
> Task / Issue flow

done

**Comment by Eugen-Ts** [comment]
> Jira – Dashboards

done

**Comment by Eugen-Ts** [comment]
> Jira – Filters, Bulk Tasks Edit

done

**Comment by Eugen-Ts** [comment]
> Test Plan vs Test Strategy

done

**Comment by scholokov** [comment]
создан новый урок
Verification VS Validation
добавлен в курс
Verification VS Validation
в блок
Теория тестирования

**Comment by scholokov** [comment]
создан новый урок
Log Files
добавлен в курс
Log Files
в блок
Особенности тестирования на различных платформах

**Comment by scholokov** [comment]
создан новый урок
SDLC / STLC
добавлен в курс
SDLC/STLC
в блок
Процессы

**Comment by scholokov** [comment]
создан новый урок
Методология Kanban
добавлен в курс
Agile / SCRUM / Kanban
в блок
Процессы

**Comment by scholokov** [comment]
создан новый урок
HTML & CSS Валидаторы
добавлен в курс
HTML & CSS Валидаторы
в блок
Web technologies

**Comment by scholokov** [comment]
создан новый урок
Introduction
добавлен в курс
API
в блок
Web technologies
