### ISSUE TITLE
Course "Fundamentals of Internet technologies applied for Websites (Client-server model)": lesson "Fundamentals of Internet technologies applied for Websites (Client-server model)" - wrong author of the lesson

### ISSUE THREAD

**Issue by Tipaieva** [scholokov/qax-portal#60]
### Discription:
At the end of the lesson "Fundamentals of Internet technologies applied for Websites (Client-server model)" marked wrong author of the lesson

### Steps:
1. Open site
2. Select "QA Программа" - "Fundamentals of Internet technologies applied for Websites (Client-server model)" - "Course Content" - 
3. Click "Fundamentals of Internet technologies applied for Websites (Client-server model)" (https://portal.qax-camp.com.ua/courses/fundamentals-of-internet-technologies-applied-for-websites-client-server-model/lessons/fundamentals-of-internet-technologies-applied-for-websites-client-server-model/) and go to at the end of the lesson

### Actual:
Denis Scholokov is listed as the author of the lesson

### Expected:
LOMENKO ALESYA is listed as the author of the lesson

### Environment:
Decktop/ Windows 10 Pro/ Google Chrome 95.0.4638.69 (64 bit)

### Attachments:
![image](https://user-images.githubusercontent.com/92110820/141508513-500a0192-64ee-4776-bda9-925a4eb7e984.png)

**Comment by scholokov** [comment]
Сhange the author of the lesson from Denis Scholokov to Lomenko Alesya
это лишняя фраза в багах. так может писать только ПМ в своих задачах, мы просто константируем факт

**Comment by scholokov** [comment]
еще так, как существует прямая уникальная линка на урок, то его есть смысл вставлять тоже

**Comment by scholokov** [comment]
fixed

**Comment by Tipaieva** [comment]
verified, the bug remained uncorrected

**Comment by scholokov** [comment]
fixed

**Comment by Tipaieva** [comment]
verified
