### ISSUE TITLE
Course REST, SOAP, API: lesson REST API Testing - wrong author of the lesson

### ISSUE THREAD

**Issue by Tipaieva** [scholokov/qax-portal#61]
### Discription:
At the end of the lesson "REST API Testing" marked wrong author of the lesson. Сhange the author of the lesson from Denis Scholokov to Andrey Samoilenko

### Steps:

1. Open site
2. Select "QA Программа" - "REST, SOAP, API"
3. Click "REST API Testing" and go to at the end of the lesson

### Actual:
Denis Scholokov is listed as the author of the lesson

### Expected:
**Andrey Samoilenko** is listed as the author of the lesson

### Environment:
Decktop/ Windows 10 Pro/ Google Chrome 95.0.4638.69 (64 bit)

### Attachments:
![image](https://user-images.githubusercontent.com/92110820/141684423-f98309b6-1803-41a4-bf85-7d5a0ef6ed11.png)

**Comment by scholokov** [comment]
удобнее, если будет присутствовать прямая ссылка

**Comment by scholokov** [comment]
fixed

**Comment by Tipaieva** [comment]
verified
