### ISSUE TITLE
Course Типы Web-атак - wrong uathor of the lesson Типы Web-атак

### ISSUE THREAD

**Issue by Tipaieva** [scholokov/qax-portal#62]
### Discription:
At the end of the lesson "Типы Web-атак" marked wrong author of the lesson. 

### Steps:

1. Open site
2. Select QA Программа - Типы Web-атак - Типы Web-атак (https://portal.qax-camp.com.ua/courses/%d1%82%d0%b8%d0%bf%d1%8b-web-%d0%b0%d1%82%d0%b0%d0%ba/lessons/%d1%82%d0%b8%d0%bf%d1%8b-web-%d0%b0%d1%82%d0%b0%d0%ba/)
### Actual:
Denis Scholokov is listed as the author of the lesson

### Expected:
**Tatiana Putchenko** is listed as the author of the lesson

### Environment:
Decktop/ Windows 10 Pro/ Google Chrome 95.0.4638.69 (64 bit)

### Attachments:
![image](https://user-images.githubusercontent.com/92110820/141690940-310b3931-0ec2-432d-b5db-bf5975197f95.png)

**Comment by scholokov** [comment]
fixed

**Comment by Tipaieva** [comment]
verified
