### ISSUE TITLE
Course SQL: lesson Базы данных – Что это такое и с чем их едят - wrong author of the lesson

### ISSUE THREAD

**Issue by Tipaieva** [scholokov/qax-portal#63]
### Discription:
At the end of the lesson "Базы данных – Что это такое и с чем их едят" marked wrong author of the lesson. 

### Steps:

1. Open site
2. Select "QA Программа" - "SQL" - "Базы данных – Что это такое и с чем их едят" (https://portal.qax-camp.com.ua/courses/sql/lessons/%d0%b1%d0%b0%d0%b7%d1%8b-%d0%b4%d0%b0%d0%bd%d0%bd%d1%8b%d1%85-%d1%87%d1%82%d0%be-%d1%8d%d1%82%d0%be-%d1%82%d0%b0%d0%ba%d0%be%d0%b5-%d0%b8-%d1%81-%d1%87%d0%b5%d0%bc-%d0%b8%d1%85-%d0%b5%d0%b4%d1%8f/)
3. Go to at the end of the lesson

### Actual:
Denis Scholokov is listed as the author of the lesson

### Expected:
**Rudchenko Yuliya** is listed as the author of the lesson

### Environment:
Decktop/ Windows 10 Pro/ Google Chrome 95.0.4638.69 (64 bit)

### Attachments:
![image](https://user-images.githubusercontent.com/92110820/142039302-2721829f-c8eb-478b-9cef-24270efbc73b.png)

**Comment by scholokov** [comment]
fixed

**Comment by Tipaieva** [comment]
verified
