### ISSUE TITLE
Course "SQL": lesson "SQL – Основы выборки данных" - wrong author of the lesson

### ISSUE THREAD

**Issue by Tipaieva** [scholokov/qax-portal#64]
### Discription:
At the end of the lesson "SQL – Основы выборки данных" marked wrong author of the lesson.

### Steps:

1. Open site
2. Select "QA Программа" - "SQL" - "SQL – Основы выборки данных" (https://portal.qax-camp.com.ua/courses/sql/lessons/sql-%d0%be%d1%81%d0%bd%d0%be%d0%b2%d1%8b-%d0%b2%d1%8b%d0%b1%d0%be%d1%80%d0%ba%d0%b8-%d0%b4%d0%b0%d0%bd%d0%bd%d1%8b%d1%85/)
3. Go to at the end of the lesson

### Actual:
Denis Scholokov is listed as the author of the lesson

### Expected:
**Rudchenko Yuliya** is listed as the author of the lesson

### Environment:
Decktop/ Windows 10 Pro/ Google Chrome 95.0.4638.69 (64 bit)

### Attachments:
![image](https://user-images.githubusercontent.com/92110820/142041692-520a4b38-f740-4fa0-8020-18f172e2554a.png)

**Comment by scholokov** [comment]
fixed

**Comment by Tipaieva** [comment]
verified
