### ISSUE TITLE
Course "SQL": lesson "Еще немного SQL" - wrong author of the lesson

### ISSUE THREAD

**Issue by Tipaieva** [scholokov/qax-portal#66]
### Discription:
At the end of the lesson "Еще немного SQL" marked wrong author of the lesson.

### Steps:

1. Open site
2. Select "QA Программа" - "SQL" - "Еще немного SQL" (https://portal.qax-camp.com.ua/courses/sql/lessons/%d0%b5%d1%89%d0%b5-%d0%bd%d0%b5%d0%bc%d0%bd%d0%be%d0%b3%d0%be-sql/)
3. Go to at the end of the lesson

### Actual:
Denis Scholokov is listed as the author of the lesson

### Expected:
**Rudchenko Yuliya** is listed as the author of the lesson

### Environment:
Decktop/ Windows 10 Pro/ Google Chrome 95.0.4638.69 (64 bit)

### Attachments:
![image](https://user-images.githubusercontent.com/92110820/142044724-c726f894-923e-474b-93cf-314ed4791e37.png)

**Comment by scholokov** [comment]
fixed

**Comment by Tipaieva** [comment]
verified
