### ISSUE TITLE
Course SDLC / STLC: lesson SDLC - wrong author of the lesson

### ISSUE THREAD

**Issue by Tipaieva** [scholokov/qax-portal#67]
### Discription:
At the end of the lesson "SDLC" marked wrong author of the lesson

### Steps:

1. Open site
2. Select "QA Программа" - "SDLC / STLC" - "SDLC" (https://portal.qax-camp.com.ua/courses/sdlc-stlc/lessons/sdlc/)
3. Go to at the end of the lesson

### Actual:
Denis Scholokov is listed as the author of the lesson

### Expected:
LOMENKO ALESYA is listed as the author of the lesson

### Environment:
Decktop/ Windows 10 Pro/ Google Chrome 95.0.4638.69 (64 bit)

### Attachments:
![image](https://user-images.githubusercontent.com/92110820/142217435-46549051-196b-4cca-8ca6-521b7606ac70.png)

**Comment by scholokov** [comment]
fixed

**Comment by Tipaieva** [comment]
verified
