### ISSUE TITLE
Course SDLC / STLC: lesson Task/Issue workflow: creation and processing of tasks and issues - wrong author of the lesson

### ISSUE THREAD

**Issue by Tipaieva** [scholokov/qax-portal#68]
### Discription:
At the end of the lesson "Task/Issue workflow: creation and processing of tasks and issues" marked wrong author of the lesson

### Steps:

1. Open site
2. Select "QA Программа" - "SDLC / STLC" - "Task/Issue workflow: creation and processing of tasks and issues" (https://portal.qax-camp.com.ua/courses/sdlc-stlc/lessons/task-issue-workflow-creation-and-processing-of-tasks-and-issues/)
3. Go to at the end of the lesson

### Actual:
Denis Scholokov is listed as the author of the lesson

### Expected:
LOMENKO ALESYA is listed as the author of the lesson

### Environment:
Decktop/ Windows 10 Pro/ Google Chrome 95.0.4638.69 (64 bit)

### Attachments:
![image](https://user-images.githubusercontent.com/92110820/142218843-caba21ae-ceed-4e95-a874-16f6d85bf2d8.png)

**Comment by scholokov** [comment]
fixed

**Comment by Tipaieva** [comment]
verified
