### ISSUE TITLE
Course "Agile / SCRUM": lesson "Introduction to Agile/SCRUM" - wrong author of the lesson

### ISSUE THREAD

**Issue by Tipaieva** [scholokov/qax-portal#69]
### Discription:
At the end of the lesson "Introduction to Agile/SCRUM" marked wrong author of the lesson

### Steps:
1. Open site
2. Select "QA Программа" - "Agile / SCRUM" - "Introduction to Agile/SCRUM" (https://portal.qax-camp.com.ua/courses/agile-scrum/lessons/introduction-to-agile-scrum/)
3. Go to at the end of the lesson

### Actual:
Denis Scholokov is listed as the author of the lesson

### Expected:
LOMENKO ALESYA is listed as the author of the lesson

### Environment:
Decktop/ Windows 10 Pro/ Google Chrome 95.0.4638.69 (64 bit)

### Attachments:
![image](https://user-images.githubusercontent.com/92110820/142223601-8a402901-6730-4e26-ac92-a1ada87a0164.png)

**Comment by scholokov** [comment]
fixed

**Comment by Tipaieva** [comment]
this lesson has been deleted

verified
