### ISSUE TITLE
Course "Agile / SCRUM": lesson "SCRUM & Kanban" - marked one author instead of two authors of the lesson

### ISSUE THREAD

**Issue by Tipaieva** [scholokov/qax-portal#70]
### Discription:
At the end of the lesson "SCRUM & Kanban" marked one author instead of two authors

### Steps:

1. Open site
2. Select "QA Программа" - "Agile / SCRUM" - "SCRUM & Kanban" (https://portal.qax-camp.com.ua/courses/agile-scrum/lessons/scrum-kanban/)
3. Go to at the end of the lesson

### Actual:
Denis Scholokov is marked as the author of the lesson

### Expected:
Denis Scholokov and LOMENKO ALESYA is marked as the authors of the lesson

### Environment:
Decktop/ Windows 10 Pro/ Google Chrome 95.0.4638.69 (64 bit)

### Attachments:
![image](https://user-images.githubusercontent.com/92110820/142226876-3f803337-7c8a-43f3-9935-a486fec8f4b5.png)

**Comment by scholokov** [comment]
fixed

**Comment by Tipaieva** [comment]
at the meeting on 18.11.2021 it was diceded to use only one author

verified
