### ISSUE TITLE
Course "Agile / SCRUM" - one video duplicated in two lessons

### ISSUE THREAD

**Issue by Tipaieva** [scholokov/qax-portal#71]
### Discription:
The video "Introduction to Agile/SCRUM - QAX all PMs (2021-04-12 at 10:20 GMT-7)" duplicated in two lessons as: 
"Introduction to Agile/SCRUM" (https://portal.qax-camp.com.ua/courses/agile-scrum/lessons/introduction-to-agile-scrum/)
and "SCRUM & Kanban" (https://portal.qax-camp.com.ua/courses/agile-scrum/lessons/scrum-kanban/)

### Steps:

1. Open site
2. Select "QA Программа" - "Agile / SCRUM" - "SCRUM & Kanban" (https://portal.qax-camp.com.ua/courses/agile-scrum/lessons/scrum-kanban/)
3. Find the video "Introduction to Agile/SCRUM - QAX all PMs (2021-04-12 at 10:20 GMT-7)"

### Actual:
video "Introduction to Agile/SCRUM - QAX all PMs (2021-04-12 at 10:20 GMT-7)" is present in the lesson

### Expected:
video "Introduction to Agile/SCRUM - QAX all PMs (2021-04-12 at 10:20 GMT-7)" is missing in the lesson

### Environment:
Decktop/ Windows 10 Pro/ Google Chrome 95.0.4638.69 (64 bit)

### Attachments:
![image](https://user-images.githubusercontent.com/92110820/142235205-a741980f-5cd8-49c6-a574-e750ceff2734.png)

**Comment by scholokov** [comment]
fixed

**Comment by Tipaieva** [comment]
verified
