### ISSUE TITLE
Course SQL - wrong author of the course

### ISSUE THREAD

**Issue by Tipaieva** [scholokov/qax-portal#72]
### Discription:
At the end of the Course Content SQL page marked wrong author of the course

### Steps:
1. Open site
2. Select "QA Программа" - "SQL" (https://portal.qax-camp.com.ua/courses/sql/)
3. Go to at the end of the Course Content SQL page

### Actual:
Denis Scholokov is marked as the author of the course

### Expected:
**Rudchenko Yuliya** is marked as the author of the course

### Environment:
Decktop/ Windows 10 Pro/ Google Chrome 95.0.4638.69 (64 bit)

### Attachments:
![image](https://user-images.githubusercontent.com/92110820/142251541-8119d1dd-f4d8-4825-98bf-814843846006.png)

**Comment by scholokov** [comment]
fixed

**Comment by Tipaieva** [comment]
verified
