### ISSUE TITLE
Check block of lessons #4 “Особенности тестирования на различных платформах”

### ISSUE THREAD

**Issue by alexandersamukha** [scholokov/qax-portal#77]
Check block of lessons #4 “Особенности тестирования на различных платформах” by link:
https://docs.google.com/spreadsheets/d/1LkrguJrv4dOF9T8rwai_6JRBGm83qjxb7baEXKASgBs/edit#gid=0

Need to check:

All videos were transferred from old version
Author name specified
Define test need (fillful test status in column «Тесты готовые»)

**Comment by Tipaieva** [comment]
table supplemented https://docs.google.com/spreadsheets/d/1LkrguJrv4dOF9T8rwai_6JRBGm83qjxb7baEXKASgBs/edit#gid=0
Videos moved
Author verified
no tests
