### ISSUE TITLE
Check block of lessons #6 “Процессы”

### ISSUE THREAD

**Issue by alexandersamukha** [scholokov/qax-portal#79]
Check block of lessons #6 “Процессы” by link:
https://docs.google.com/spreadsheets/d/1LkrguJrv4dOF9T8rwai_6JRBGm83qjxb7baEXKASgBs/edit#gid=0

Need to check:

All videos were transferred from old version
Author name specified
Define test need (fillful test status in column «Тесты готовые»)

**Comment by Tipaieva** [comment]
#67 
#68 
#69 
#70 
#71

**Comment by Tipaieva** [comment]
verified

videos is moved
author is specified
no tests
