### ISSUE TITLE
Check block of lessons #7 “Web technologies”

### ISSUE THREAD

**Issue by alexandersamukha** [scholokov/qax-portal#80]
Check block of lessons #7 “Web technologies” by link:
https://docs.google.com/spreadsheets/d/1LkrguJrv4dOF9T8rwai_6JRBGm83qjxb7baEXKASgBs/edit#gid=0

Need to check:

All videos were transferred from old version
Author name specified
Define test need (fillful test status in column «Тесты готовые»)

**Comment by Tipaieva** [comment]
#60 
#62 
#61  
#73 
Videos moved in QA Программа
Authors verified
no tests

**Comment by Tipaieva** [comment]
videos moved
authors listed
no tests
