### ISSUE TITLE
Course SQL - is not included the article "SQL Шпаргалка" 

### ISSUE THREAD

**Issue by Tipaieva** [scholokov/qax-portal#84]
### Description:
In the SQL course is not included the article "SQL Шпаргалка" (https://portal.qax-camp.com.ua/sql-help/)

### Steps:

1. Open site
2. Select QA Программа - SQL (https://portal.qax-camp.com.ua/courses/sql/)

### Actual:
the article "SQL Шпаргалка" **is NOT included** in the SQL course

### Expected:
the article "SQL Шпаргалка" **is included** in the SQL course

### Environment:
Desctop / Windows 10 Pro/ Google Chrome 95.0.4638.69 (64 bit)

### Attachments:
![image](https://user-images.githubusercontent.com/92110820/142817629-92f6eff2-37a7-4c7a-9d5b-c928695c766d.png)

#82

**Comment by scholokov** [comment]
материал устарел и перемещен в:
https://portal.qax-camp.com.ua/courses/old/

**Comment by Tipaieva** [comment]
verified
