### ISSUE TITLE
Course Введение в тестирование - wrong author of the Course Content

### ISSUE THREAD

**Issue by Tipaieva** [scholokov/qax-portal#85]
### Description:
At the end of the Course Content Введение в тестирование ПО marked wrong author of the Course Content

### Steps:
1. Open site
2. Select QA Программа - Введение в тестирование ПО (https://portal.qax-camp.com.ua/courses/%d0%b2%d0%b2%d0%b5%d0%b4%d0%b5%d0%bd%d0%b8%d0%b5-%d0%b2-%d1%82%d0%b5%d1%81%d1%82%d0%b8%d1%80%d0%be%d0%b2%d0%b0%d0%bd%d0%b8%d0%b5-%d0%bf%d0%be/)

### Actual:
Denis Scholokov is marked as the author of the Course Content

### Expected:
**Rudchenko Yuliya** is marked as the author of the Course Content

### Environment:
Decktop/ Windows 10 Pro/ Google Chrome 95.0.4638.69 (64 bit)

### Attachments:
![image](https://user-images.githubusercontent.com/92110820/142829452-78216539-c40d-41b1-8868-e3e765f36ce7.png)

#74

**Comment by scholokov** [comment]
fixed

**Comment by Tipaieva** [comment]
verified
