### ISSUE TITLE
Course TestRail: lesson TestRail - wrong author of the lesson

### ISSUE THREAD

**Issue by Tipaieva** [scholokov/qax-portal#86]
### Discription:
At the end of the TestRail lesson marked wrong author of the lesson

### Steps:
1. Open site
2. Select QA Программа - TestRail - TestRail (https://portal.qax-camp.com.ua/courses/testrail/lessons/testrail/)
3. Go to at the end of the lesson

### Actual:
Denis Scholokov is marked as the author of the lesson

### Expected:
**Rudchenko Yuliya** is marked as the author of the lesson

### Environment:
Decktop/ Windows 10 Pro/ Google Chrome 95.0.4638.69 (64 bit)

### Attachments:
![image](https://user-images.githubusercontent.com/92110820/142839538-8e43fa29-f349-4f89-aae9-f82ade777059.png)

#75

**Comment by scholokov** [comment]
fixed

**Comment by Tipaieva** [comment]
verified
