### ISSUE TITLE
Course GitHub: lesson GitHub – How To Upload Images - the author's data is incorrectly written

### ISSUE THREAD

**Issue by Tipaieva** [scholokov/qax-portal#88]
### Description:
In the lesson GitHub – How To Upload Images the author's data is incorrectly written

### Steps:
1. Open the site
2. Select QA Программа - GitHub - GitHub – How To Upload Images (https://portal.qax-camp.com.ua/courses/github/lessons/github-how-to-upload-images/)
3. Go at the end of the lesson

### Actual:
- the name and surname of the lesson author are **written in one piece**, 
- the e-mail of the lesson author **is written**

### Expected:
- the name and surname of the lesson author are **written separately**, 
- the e-mail of the lesson author **is not written**

### Environment:
Desctop/ Windows 10 PRO/ Google Chrome 95.0.4638.69 (64 bit)

### Attacments:
![image](https://user-images.githubusercontent.com/92110820/142853850-c9e5499a-b362-42a6-a2bd-2eb122e6915e.png)

#75

**Comment by scholokov** [comment]
fixed

**Comment by Tipaieva** [comment]
verified
