### ISSUE TITLE
Course "PM and issue tracking tools. Task/Issue workflow criteria": lesson PM and issue tracking tools. Task/Issue workflow criteria - wrong author of the lesson

### ISSUE THREAD

**Issue by Tipaieva** [scholokov/qax-portal#90]
### Discription:
At the end of the lesson "PM and issue tracking tools. Task/Issue workflow criteria" marked wrong author of the lesson

### Steps:
1. Open site
2. Select "QA Программа" - "PM and issue tracking tools. Task/Issue workflow criteria" - "PM and issue tracking tools. Task/Issue workflow criteria" (https://portal.qax-camp.com.ua/courses/pm-and-issue-tracking-tools-task-issue-workflow-criteria/lessons/pm-and-issue-tracking-tools-task-issue-workflow-criteria/)
3. Go to at the end of the lesson

### Actual:
Denis Scholokov is marked as the author of the lesson

### Expected:
LOMENKO ALESYA is marked as the author of the lesson

### Environment:
Decktop/ Windows 10 Pro/ Google Chrome 96.0.4664.45 (64 bit)

### Attachments:
![image](https://user-images.githubusercontent.com/92110820/143076367-9f952ca9-ca7a-44bb-9405-62a6f152d7c5.png)
#83

**Comment by scholokov** [comment]
fixed

**Comment by Tipaieva** [comment]
verified
