### ISSUE TITLE
Course "PM and issue tracking tools. Task/Issue workflow criteria" - wrong author of the Course Content

### ISSUE THREAD

**Issue by Tipaieva** [scholokov/qax-portal#91]
### Discription:
At the end of the Course Content PM and issue tracking tools. Task/Issue workflow criteria marked wrong author of the Course Content

### Steps:
1. Open site
2. Select "QA Программа" - "PM and issue tracking tools. Task/Issue workflow criteria" (https://portal.qax-camp.com.ua/courses/pm-and-issue-tracking-tools-task-issue-workflow-criteria/)
3. Go to at the end of the Course Content

### Actual:
Denis Scholokov is marked as the author of the Course Content

### Expected:
LOMENKO ALESYA is marked as the author of the Course Content

### Environment:
Decktop/ Windows 10 Pro/ Google Chrome 96.0.4664.45 (64 bit)

### Attachments:
![image](https://user-images.githubusercontent.com/92110820/143078558-e67eecbc-9889-442e-a3ef-8879056202b2.png)
#83

**Comment by scholokov** [comment]
fixed

**Comment by Tipaieva** [comment]
verified
