### ISSUE TITLE
Course "Project estimation techniques": lesson "Project estimation techniques" - wrong author of the lesson

### ISSUE THREAD

**Issue by Tipaieva** [scholokov/qax-portal#92]
### Discription:
At the end of the lesson "Project estimation techniques" marked wrong author of the lesson

### Steps:
1. Open site
2. Select "QA Программа" - "Project estimation techniques" - "Project estimation techniques" (https://portal.qax-camp.com.ua/courses/project-estimation-techniques/lessons/project-estimation-techniques/)
3. Go to at the end of the lesson

### Actual:
Denis Scholokov is marked as the author of the lesson

### Expected:
LOMENKO ALESYA is marked as the author of the lesson

### Environment:
Decktop/ Windows 10 Pro/ Google Chrome 96.0.4664.45 (64 bit)

### Attachments:
![image](https://user-images.githubusercontent.com/92110820/143080301-20244465-5dff-445c-903a-2950dcf1c0df.png)

#83

**Comment by scholokov** [comment]
fixed

**Comment by Tipaieva** [comment]
verified
