### ISSUE TITLE
Course "Project estimation techniques" - wrong author of the Course Content

### ISSUE THREAD

**Issue by Tipaieva** [scholokov/qax-portal#93]
### Discription:
At the end of the Course Content "Project estimation techniques" marked wrong author of the Course Content

### Steps:
1. Open site
2. Select "QA Программа" - "Project estimation techniques" (https://portal.qax-camp.com.ua/courses/project-estimation-techniques/)
3. Scroll down to the author of the Course Content

### Actual:
Denis Scholokov is marked as the author of the Course Content

### Expected:
LOMENKO ALESYA is marked as the author of the Course Content

### Environment:
Decktop/ Windows 10 Pro/ Google Chrome 96.0.4664.45 (64 bit)

### Attachment:
![image](https://user-images.githubusercontent.com/92110820/143081229-ca3e7dcd-e242-48b6-9bdb-3ba17fab197d.png)

#83

**Comment by scholokov** [comment]
fixed

**Comment by Tipaieva** [comment]
verified
