### ISSUE TITLE
Course "Decomposition of tasks: what is it and why is it needed?": lesson "Decomposition of tasks: what is it and why is it needed?" - wrong author of the lesson

### ISSUE THREAD

**Issue by Tipaieva** [scholokov/qax-portal#94]
### Discription:
At the end of the lesson "Decomposition of tasks: what is it and why is it needed?" marked wrong author of the lesson

### Steps:
1. Open site
2. Select "QA Программа" - "Decomposition of tasks: what is it and why is it needed?" - "Decomposition of tasks: what is it and why is it needed?" (https://portal.qax-camp.com.ua/courses/decomposition-of-tasks-what-is-it-and-why-is-it-needed/lessons/decomposition-of-tasks-what-is-it-and-why-is-it-needed/)
3. Scroll down to the author of the lesson

### Actual:
Denis Scholokov is marked as the author of the lesson

### Expected:
LOMENKO ALESYA is marked as the author of the lesson

### Environment:
Decktop/ Windows 10 Pro/ Google Chrome 96.0.4664.45 (64 bit)

### Attachments:
![image](https://user-images.githubusercontent.com/92110820/143082386-98814d29-e38f-43bb-96a2-0e5308032524.png)

#83

**Comment by scholokov** [comment]
fixed

**Comment by Tipaieva** [comment]
verified
