### ISSUE TITLE
Course "Decomposition of tasks: what is it and why is it needed?" - wrong author of the Course Content

### ISSUE THREAD

**Issue by Tipaieva** [scholokov/qax-portal#95]
### Discription:
At the end of the Course Content "Decomposition of tasks: what is it and why is it needed?" marked wrong author of the Course Content

### Steps:
1. Open site
2. Select "QA Программа" - "Decomposition of tasks: what is it and why is it needed?" (https://portal.qax-camp.com.ua/courses/decomposition-of-tasks-what-is-it-and-why-is-it-needed/)
3. Scroll down to the author of the Course Content

### Actual:
Denis Scholokov is marked as the author of the Course Content 

### Expected:
LOMENKO ALESYA is marked as the author of the Course Content 

### Environment:
Decktop/ Windows 10 Pro/ Google Chrome 96.0.4664.45 (64 bit)

### Attachments:
![image](https://user-images.githubusercontent.com/92110820/143082956-7735abb4-3aea-440c-b265-7d6459f389c0.png)

#83

**Comment by scholokov** [comment]
fixed

**Comment by Tipaieva** [comment]
verified
