### ISSUE TITLE
Course "PM documentations / artifacts": lesson "PM documentations / artifacts" - wrong author of the lesson

### ISSUE THREAD

**Issue by Tipaieva** [scholokov/qax-portal#96]
### Discription:
At the end of the lesson "PM documentations / artifacts" marked wrong author of the lesson

### Steps:
1. Open site
2. Select "QA Программа" - "PM documentations / artifacts" - "PM documentations / artifacts" (https://portal.qax-camp.com.ua/courses/pm-documentations-artifacts/lessons/pm-documentations-artifacts/)
3. Scroll down to the author of the lesson

### Actual:
Denis Scholokov is marked as the author of the lesson

### Expected:
LOMENKO ALESYA is marked as the author of the lesson

### Environment:
Decktop/ Windows 10 Pro/ Google Chrome 96.0.4664.45 (64 bit)

### Attachments:
![image](https://user-images.githubusercontent.com/92110820/143084701-cdfb04e8-d4fc-4732-b0c6-f3cd0f153ffe.png)

#83

**Comment by scholokov** [comment]
fixed

**Comment by Tipaieva** [comment]
verified
