### ISSUE TITLE
Course PM documentations / artifacts - wrong author of the Course Content 

### ISSUE THREAD

**Issue by Tipaieva** [scholokov/qax-portal#97]
### Discription:
At the end of the Course Content 'PM documentations / artifacts" marked wrong author of the Course Content 

### Steps:
1. Open site
2. Select "QA Программа" - "PM documentations / artifacts" (https://portal.qax-camp.com.ua/courses/pm-documentations-artifacts/)
3. Scroll down to the author of the Course Content

### Actual:
Denis Scholokov is marked as the author of the Course Content

### Expected:
LOMENKO ALESYA is marked as the author of the Course Content

### Environment:
Decktop/ Windows 10 Pro/ Google Chrome 96.0.4664.45 (64 bit)

### Attachment:
![image](https://user-images.githubusercontent.com/92110820/143086069-dddbc555-eef7-4a1a-ac6d-d745d80f8bda.png)

#83

**Comment by scholokov** [comment]
fixed

**Comment by Tipaieva** [comment]
verified
