### ISSUE TITLE
QA Программе - course "Тест Дизайн – Техники" is missing

### ISSUE THREAD

**Issue by Tipaieva** [scholokov/qax-portal#99]
### Description:
In the QA Программе the course "Тест Дизайн – Техники" (https://portal.qax-camp.com.ua/test-design/) is missing

### Steps:
1. Open site
2. Select QA Программa https://portal.qax-camp.com.ua/qa-program/

### Actual:
course "Тест Дизайн – Техники" **is missing** in the QA Программa

### Expected:
course "Тест Дизайн – Техники" **is present** in the QA Программa

### Environment:
Desctop/Wondows 10 Pro/ Google Chrome 96.0.4664.45 (64 bit)

### Attachment:
![image](https://user-images.githubusercontent.com/92110820/143433021-fcfed958-aa3b-44a8-bdda-aa5b17147152.png)

**Comment by MykhailoBorovikov** [comment]
Bug already fixed and verified
